### ISSUE TITLE
Geopy with Nominatim doesn't work

### ISSUE THREAD

**Issue by ustroetz** [geopy/geopy#103]
I am trying to geocode the following address:
```
geolocatorNominatim.geocode('Av. Universidad, Coyoacán, Mexico City, Federal District, 01090, Mexico')
```

The error I am getting is the following:
```
   print geolocatorNominatim.geocode('Av. Universidad, Coyoacán, Mexico City, Federal District, 01090, Mexico')
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/osm.py", line 176, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/site-packages/geopy/geocoders/base.py", line 156, in _call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out
```

Can someone reproduce that?

**Comment by ijl** [comment]
@ustroetz this means the Nominatim service didn't return a result in time. It's to be expected sometime; you need to account for the possibility with any remote service.

**Comment by ustroetz** [comment]
Ah okay. I figured if I set the `timeout=10` parameter I don't run into this problem. Thanks for the hint!

**Comment by ijl** [comment]
Yeah, Nominatim is usually fast for me, but they may've been unavailable then or you may have had a network issue.
