### ISSUE TITLE
Find venues near an address

### ISSUE THREAD

**Issue by dashesy** [geopy/geopy#110]
Thanks for the great tool! I have looked at the documentations but still there are some questions with regard to what can geopy achieve now and what can be added to it (if a service is already available).
Looking at [geocoder](https://github.com/alexreisner/geocoder) it seems some services can be used to return venues near an address, 

* Is it possible to do a similar search (find venues) using `geopy`? 
* Specially is it possible to get list of  e.g. restaurants near some latitude, longitude?
* If `geopy` does not have this options, is it possible to do in theory?

**Comment by ijl** [comment]
@dashesy you would need to find a service that supports it. geopy is just a client library for such services, with no functionality like that supported now.
