### ISSUE TITLE
Is it possible to get only the nearest city?

### ISSUE THREAD

**Issue by MartinThoma** [geopy/geopy#111]
When I have some coordinates, is it possible to get only the name of the closest city (not the street name / zip code / country, but only the city)?

**Comment by solumos** [comment]
This may depend somewhat on which geocoder you are using, but generally address formatting is not consistent accross locations. See the first answer [here](http://stackoverflow.com/questions/11160192/how-to-parse-freeform-street-postal-address-out-of-text-and-into-components).

**Comment by ijl** [comment]
@MartinThoma you can parse the `Location.raw` attribute of a reverse query to find the city it falls in or, if the service exposes it, the nearest city.
