### ISSUE TITLE
Insufficient Priveleges for Nominatim

### ISSUE THREAD

**Issue by solumos** [geopy/geopy#112]
When using Nominatim, we get an geopy.exc.GeocoderInsufficientPrivileges exception, even though Nominatim should not require account credentials:

    >>> geolocator = Nominatim()
    >>> geolocator.geocode("Washington, DC", timeout=10) 
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/osm.py", line 191, in geocode
        self._call_geocoder(url, timeout=timeout), exactly_one
      File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 147, in _call_geocoder
        raise ERROR_CODE_MAP[code](message)
    geopy.exc.GeocoderInsufficientPrivileges: HTTP Error 403: Forbidden

Can anyone else confirm?

**Comment by carolinux** [comment]
yes, also got that

**Comment by solumos** [comment]
Perhaps the Error 403 is due to requests being blocked. I found [this post](https://help.openstreetmap.org/questions/24740/why-am-i-all-of-a-sudden-getting-error-403) suggesting that the [usage policy](http://wiki.openstreetmap.org/wiki/Nominatim_usage_policy#Requirements) is being violated. Maybe an HTTP Referer or User-Agent is necessary, long-term?

**Comment by trukvl** [comment]
This issue seems to be caused by OSM changing the view box parameter from 'view_box' to 'viewbox'.  I verified this by printing the log message from geopy with the geocode URL, copying it into a browser and changing it.  Then I changed osm.py on my system, replacing 'view_box' with 'viewbox' in all instances.  I have a branch with the change that I can push.

**Comment by solumos** [comment]
It looks like OSM added backwards compatibility for the 'view_box' parameter.
[viewbox](http://nominatim.openstreetmap.org/search?q=Chicago+IL&viewbox=[-180%2C+-90%2C+180%2C+90]&format=json)
[view_box](http://nominatim.openstreetmap.org/search?q=Chicago+IL&view_box=[-180%2C+-90%2C+180%2C+90]&format=json)

**Comment by tobiz** [comment]
I've started getting this error today from my program 13th Apr 2016, I didn't get it a few days ago and I've changed nothing.  Also tested this from the command line running simple examples and get same result. I've now updated to geopy 1.11.0 from 1.10.0 and same result.
File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/osm.py", line 193, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/usr/local/lib/python2.7/dist-packages/geopy/geocoders/base.py", line 158, in _call_geocoder
    raise ERROR_CODE_MAP[code](message)
geopy.exc.GeocoderInsufficientPrivileges: HTTP Error 403: Forbidden

**Comment by Jeffkrop** [comment]
This started happening to me today also. I posted it here http://stackoverflow.com/questions/36599584/geopy-error-and-timeout 
with no luck yet. I am only calling one location in a script for a python class.

**Comment by tobiz** [comment]
I changed from Nominatim() to geopy.geocoders.GoogleV3() and it now works; this may help someone find the problem.

**Comment by Jeffkrop** [comment]
tobiz can you post some code?

**Comment by Vixen25** [comment]
same here! It happened yesterday to me, and it still doesn't work ... any idea? I can't switch to google geocoded since I'm reverse-geocoding and they provide different addresses format (I should change my whole database)

**Comment by tobiz** [comment]
The code is self explanatory (I hope!)

The exception code was added to find out what was going wrong - it just 
confirmed what I knew but it helped me to change the code calling 
get_coords to get the values I wanted anyway (the geocode option is 
useful but not essential).

After some research I found there are other geocoders so tried GoogleV3 
and the problem has gone away.

-----------------------------------------
def get_coords(address):
     try:
#        geolocator = Nominatim(timeout=3, scheme='http')  # Nominatim 
seems to have stopped working, see github geopy
         geolocator = geopy.geocoders.GoogleV3(timeout=3)
         try:
             location = geolocator.geocode(address, timeout=3, 
exactly_one=True)  # Only 1 location for this address
             if location == None:
                 print "Geocoder Service timed out or Airfield: ", 
address, " not known by geocode locator service. Check settings"
                 return False
             ele = geocoder.elevation(address)
             print "Geolocator worked"
             return location.latitude, location.longitude, ele.meters
         except ERROR_CODE_MAP[400]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[400]
         except ERROR_CODE_MAP[401]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[401]
         except ERROR_CODE_MAP[402]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[402]
         except ERROR_CODE_MAP[403]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[403]
         except ERROR_CODE_MAP[407]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[407]
         except ERROR_CODE_MAP[412]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[412]
         except ERROR_CODE_MAP[413]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[413]
         except ERROR_CODE_MAP[414]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[414]
         except ERROR_CODE_MAP[502]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[502]
         except ERROR_CODE_MAP[503]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[503]
         except ERROR_CODE_MAP[504]:
             print " ERROR_CODE_MAP is: ",  ERROR_CODE_MAP[503]
         return False
     except GeocoderTimedOut as e:
         time.sleep(1)
         print "Geocoder Service timed out for Airfield: ", address
         return False



----------------------------------------


Hope that helps you solve your problem; if not, interesting!

Peter J Robinson

*Email:* pjrobinson@metronet.co.uk
*Sip:*     tobizlinphone1@sip.linphone.org
*Sip:*     tobiz@ekiga.net

**Comment by Jeffkrop** [comment]
Thank you. It returns less information for the Address but it will have to do for now.

**Comment by daviddunne** [comment]
I have started getting the same issue yesterday myself, Im handling the exception by using a Google geolocator as a backup for now.

**Comment by edwin34** [comment]
![program](https://user-images.githubusercontent.com/36815243/36641463-b5b021c4-1a55-11e8-9038-721d314d1368.png)
![error403](https://user-images.githubusercontent.com/36815243/36641467-bd9e969a-1a55-11e8-9f18-af7f992c4653.png)

**Comment by psawamura** [comment]
I'm also getting the same error. 

![image](https://user-images.githubusercontent.com/32387702/37204628-d981df76-2391-11e8-9847-31e93ceca1c4.png)
![image](https://user-images.githubusercontent.com/32387702/37204641-e861a440-2391-11e8-82d9-23423adc0670.png)

**Comment by edwin34** [comment]
Ya issue still persists!!

**Comment by EmmanuelObo** [comment]
Getting the same thing with Django

```
Request Method: | POST
-- | --
http://127.0.0.1:8000/entry/create/
1.11.5


```

**Comment by KostyaEsmukov** [comment]
Nominatim returns `HTTP Error 403: Forbidden` when [their ToS](https://operations.osmfoundation.org/policies/nominatim/) are violated. The reasons might be:

1. non-unique user-agent. geopy since 1.12.0 [supports passing custom user_agent](http://geopy.readthedocs.io/en/1.12.0/#geopy.geocoders.Nominatim.__init__) like this:
```
>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim(user_agent="my-application")
```
Actually [this is stated](http://geopy.readthedocs.io/en/1.12.0/#geopy.geocoders.Nominatim) in the docs.

2. High volume of requests (Nominatim rate limits are quite low – no more than 1 request per second). In this case you're better off switching to another geocoding service (try MapQuest or Photon as close alternatives based on OSM).

If anyone is willing to help with adding ToS to documentation – see #268.

**Comment by renatoosousa** [comment]
same error here

**Comment by geronimogarcia3** [comment]
changed to this and no longer got error:

`geolocator = Nominatim(user_agent="my-application")`

**Comment by ireneraissa** [comment]
Nominatim returns HTTP Error 403: Forbidden
I just used GoogleV3 and it works

**Comment by tobiz** [comment]
I had a similar problem; I just left it for a while and it now works again.  I think the problem was at the sever end.

**Comment by Developer-Felix** [comment]
0

"GeocoderInsufficientPrivileges" error - try to use 'Photon' instead of 'Nominatim'

from geopy.geocoders import Photon
geolocator = Photon(user_agent="app_name here")
