### ISSUE TITLE
IL, USA doesn't find results but Illinois, USA does and NY, USA does as well

### ISSUE THREAD

**Issue by sshum00** [geopy/geopy#116]
>>> print geolocator.geocode("IL, USA").raw
{u'display_name': u'United States of America', u'importance': 0.944692348398, u'
place_id': u'127658196', u'lon': u'-100.4458825', u'lat': u'39.7837304', u'osm_t
ype': u'relation', u'licence': u'Data \xa9 OpenStreetMap contributors, ODbL 1.0.
 http://www.openstreetmap.org/copyright', u'osm_id': u'148838', u'boundingbox':
[u'-14.7608357', u'71.6048217', u'-179.9999999', u'180'], u'type': u'administrat
ive', u'class': u'boundary', u'icon': u'https://nominatim.openstreetmap.org/imag
es/mapicons/poi_boundary_administrative.p.20.png'}

Doesn't give me the proper results :'(

**Comment by ijl** [comment]
@sshum00 this is an issue with Nominatim's search results rather than geopy, so you'll need to file a ticket with the service, here: https://trac.openstreetmap.org/query?status=new&status=assigned&status=reopened&component=nominatim&order=id&desc=1
