### ISSUE TITLE
Add customized http request User-Agent header

### ISSUE THREAD

**Issue by sebastianneubauer** [geopy/geopy#117]
My application that uses geopy was blocked by Nominatim as geopy uses the standard user agent header for requests provided by urllib (Python-urllib/2.7). Nominatim requires to add an identifying user agent header per application in order to be able to track and block requests if needed. 

In PR #115 I added such functionality, every request for all geocoders will identify with User-Agent: geopy/VERSION. In the Nominatim geocoder one can choose an arbitrary customized user agent header.

**Comment by ijl** [comment]
Fixed by #115.
