### ISSUE TITLE
No module named geocoders

### ISSUE THREAD

**Issue by rakeshsukla53** [geopy/geopy#119]
from geopy.geocoders import Nominatim

g = Nominatim()

def find():

    query = raw_input('What would you like to search')

    place = g.geocode(query)

    print place.address
    print place.latitude, place.longitude

find()

I have installed geopy==1.9.1 but still it is showing me this error

**Comment by ijl** [comment]
@rakeshsukla53 I think this is a Python path issue from your install. Do you have more details? Reopen if so.
