### ISSUE TITLE
Error in geocoding example in README?

### ISSUE THREAD

**Issue by khorton** [geopy/geopy#124]
The first example in the README for v1.1.0 appears to have an error.  If I run the example verbatim from the README, I get:

> > > geolocator = Nominatim()
> > > location = geolocator.geocode("175 5th Avenue NYC")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/sw/lib/python2.7/site-packages/geopy/geocoders/osm.py", line 192, in geocode
> > >     self._call_geocoder(url, timeout=timeout), exactly_one
> > >   File "/sw/lib/python2.7/site-packages/geopy/geocoders/base.py", line 160, in _call_geocoder
> > >     raise GeocoderServiceError(message)
> > > geopy.exc.GeocoderServiceError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

The example works without error if I add "scheme='http'" to the call to Nominatim().  E.g.

> > > geolocator = Nominatim(scheme='http')
> > > location = geolocator.geocode("175 5th Avenue NYC")
> > > print(location.address)
> > > Flatiron Building, 175, 5th Avenue, Flatiron, New York, NYC, New York, 10010, United States of America

**Comment by ijl** [comment]
@khorton I can't reproduce. That your exception is a `GeocoderServiceError` means a request was sent. Possibly this was a transitory network or Nominatim (502) issue? Is it consistent for you?

**Comment by khorton** [comment]
I get the same errors today, on two different computers.

I note that the comments in geopy.geocoders.Nominatim state that "Nominatim does not support SSL".  Does it support https, if it does not support SSL?  When I saw the SSL-related error message, and the note in the docs that SSL is not supported, I looked for a way to ensure SSL was not involved, which lead me to "scheme='http'".  What default scheme do you have set in your geopy?
--
Kevin Horton

**Comment by criptych** [comment]
> Does it support https, if it does not support SSL?

"https" basically means HTTP over SSL, so no.

> I looked for a way to ensure SSL was not involved, which lead me to "scheme='http'". What default scheme do you have set in your geopy?

It does look like the default scheme is still "https" since it's imported from `geocoders.base`.

**Comment by AbdealiJK** [comment]
I got a very similar issue. For me `.geocode()` example worked find. But the `.reverse()` example didn't. It gave the Service Not available exception.

On using `scheme='http'` it worked fine.

**Comment by tmarthal** [comment]
With the python 3.6 changes to how certifications are handled, I thought I'd share my solution to having ssl problems with the geocoder example by monkey patching the `urlopen` attribute using the `certifi` certs:

Problematic code with no certifications:

```>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim()
>>> location = geolocator.geocode("175 5th Avenue NYC")

<removed stack trace>
    page = requester(req, timeout=(timeout or self.timeout), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 223, in urlopen
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>
```

Here we pass the certifi certificates into the urlopen method:

```>>> from geopy.geocoders import Nominatim
>>> import certifi
>>> def uo(args, **kwargs):
...    return urllib.request.urlopen(args, cafile=certifi.where(), **kwargs)
... 
>>> geolocator = Nominatim()
>>> geolocator.urlopen = uo 
>>> location = geolocator.geocode("175 5th Avenue NYC")
>>> location.address
'Flatiron Building, 175, 5th Avenue, Flatiron, Manhattan, New York County, NYC, New York, 10010, United States of America'
```

Not sure if it helps this old issue, but that was the solution I came up with.

**Comment by abhi007tyagi** [comment]
where to set scheme=http?

I am also seeing SSL error on following example
`>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim()
>>> location = geolocator.geocode("175 5th Avenue NYC")
>>> print(location.address)
Flatiron Building, 175, 5th Avenue, Flatiron, New York, NYC, New York, ...
>>> print((location.latitude, location.longitude))
(40.7410861, -73.9896297241625)
>>> print(location.raw)
{'place_id': '9167009604', 'type': 'attraction', ...}`

**Comment by dterg** [comment]
Pass it as an argument to the Nominatim class:

``` 
geolocator = Nominatim(scheme='http)
```

**Comment by KostyaEsmukov** [comment]
#291 has added support for passing custom `ssl_context`. 

After geopy 1.14.0 is released (that'll be pretty soon), for anyone affected by this I suggest to do the following:
- If you're still on an older version of Python (before 2.7.9 and 3.4.3), please consider upgrading. Otherwise a warning will be issued stating that TLS verification doesn't happen.
- If you ended up using `scheme='http'`, consider switching back to the default `https` scheme along with passing a custom SSL context.
- If you were monkey-patching `urlopen` (as in the comment by @tmarthal above), please stop that, and use the following instead:

      import certifi
      import ssl
      import geopy.geocoders
      ctx = ssl.create_default_context(cafile=certifi.where())
      geopy.geocoders.options.default_ssl_context = ctx

**Comment by KostyaEsmukov** [comment]
`geopy==1.14.0` has been released 🎉
