### ISSUE TITLE
YahooFinder placefinder.py exactly_one fails on empty results

### ISSUE THREAD

**Issue by SoftwareArtisan** [geopy/geopy#125]
Line 191 placefinder.py

```
    if exactly_one:
        return results[0]
    else:
        return results
```

fails on no proper result being returned - specifically one filtered out because country code's don't match.
Throws index error.

Is this designed and expected behavior?

**Comment by ijl** [comment]
No, the spec is to return None. I'll fix this later. Thanks for reporting.

**Comment by SoftwareArtisan** [comment]
NP - let me know if you want me to lend a hand.

**Comment by micahcochran** [comment]
Related issue #190
