### ISSUE TITLE
Bing structured query does not work

### ISSUE THREAD

**Issue by Duffycola** [geopy/geopy#132]
Hi,

I've noticed the structured query for bing maps does not work. The unit tests are passing, because it ignores the unit test when the API returns nothing.

Steps to reproduce:

```
ipython
import geopy
key = 'YOURAPIKEY'
print geopy.geocoders.Bing(key).geocode({'postalCode': '80020', 'countryRegion':'United States'})
None
print geopy.geocoders.Bing(key).geocode('80020 United States')
Broomfield, CO 80020, United States
```

**Comment by KostyaEsmukov** [comment]
Just checked, works for me:

```
>>> import geopy
>>> g = geopy.geocoders.Bing('...')
>>> g.geocode({'postalCode': '80020', 'countryRegion':'United States'})
Location(Broomfield, CO 80020, United States, (39.9577751159668, -105.10954284668, 0.0))
>>> g.geocode('80020 United States')
Location(Broomfield, CO 80020, United States, (39.9577751159668, -105.10954284668, 0.0))
```

I've just pushed fd14b06 which removes the `SkipTest`s hiding the `None`s. Will see how it goes. I've never seen them in test runs anyway. Perhaps it was an issue on Bing's side, which is now fixed?
