### ISSUE TITLE
viewbox parameter in osm backend is used wrongly

### ISSUE THREAD

**Issue by lonvia** [geopy/geopy#135]
There are two serious issues with your use of the viewbox parameter in the nominatim backend:

1. It is wrongly formatted. There are brackets around the coordinates which cause some random interpretation of the coordinates on the server side.
2. The viewbox parameter is always added. This is bad because the viewbox parameter changes the search query to a geographically restricted query. It changes which results are shown and in which order they appear. The fact that the default spans the entire planet means that you get the results pretty much a random order instead in order of their importance. viewbox should only be added when explicitly requested.

**Comment by pnorman** [comment]
This could also be an issue with the MapQuest Open nominatim geocoder setup, if the code used is not in common

**Comment by m0zes** [comment]
It is not in common with OpenMapQuest at all. It appears as though OpenMapQuest geocoder doesn't have the view_box parameter.

**Comment by ijl** [comment]
Fixed by #136.
