### ISSUE TITLE
Inaccurate conversion from kilometers to miles

### ISSUE THREAD

**Issue by cffk** [geopy/geopy#146]
geopy/units.py uses the exact multiplier, 1.609344, to convert miles
into kilometers but an *approximate* multiplier, 0.621371192, to convert
kilometers into miles.  This leads to an error of about 4mm over a
quarter meridian.  Not much, you might say.  But why be so sloppy in the
first place?  Either express the multiplier with 17 significant figures
(0.62137119223733397) or divide by 1.609344.

**Comment by ijl** [comment]
@cffk, likewise, I wonder if you could contribute a pull request?

**Comment by cffk** [comment]
This is addressed in pull request #150.
