### ISSUE TITLE
Value used for EARTH_RADIUS is bogus

### ISSUE THREAD

**Issue by cffk** [geopy/geopy#147]
The figure that geopy/distance uses for EARTH_RADIUS, 6372.795 km, is
bogus.  geopy cites Wikipedia, and indeed several years ago Wikipedia
included this number (the "ellipsoidal quadratic mean radius").  However
it was contributed by an enthusiastic and early contributor to
Wikipedia, who was, unfortunately, not very mathematically
sophisticated.  The best quantity to use for an equivalent spherical
radius is the IUGG mean radius R_1 = (2*a + b) / 3 = 6371.009 km (for
WGS84) -- possibly you could round this to 6371 km.  This value
minimizes the RMS error between great-circle and geodesic distances.
For the painful deconstruction of the ellipsoidal quadratic mean radius,
see https://en.wikipedia.org/wiki/Talk:Great-circle_distance/Archive_1

**Comment by ijl** [comment]
@cffk ok, do you perhaps have time to contribute a pull request on this?

**Comment by cffk** [comment]
This is addresses in pull request #151.
