### ISSUE TITLE
More maintainers

### ISSUE THREAD

**Issue by ijl** [geopy/geopy#149]
If you'd like commit access to geopy, email me. I can still help, but don't have enough time to do this myself.

**Comment by sebastianneubauer** [comment]
do you have a rough estimate how much work/time it is?

**Comment by ijl** [comment]
Responding to others' pull requests doesn't take very much time. People can do more substantial work, as well. I think adding work to the current implementation is a bit painful as the current template approach strains with the variation needed for each geocoder. So to me the biggest unmet need is to refactor geocoders to be composable so that, e.g., requests (or custom request classes) can be used over urllib, parsing can be configured and done to extract what information the user wants from the response, and there's less code brought into any change. This is motivated by the project really being a matter of convenience and work-sharing for interacting with many geocoding APIs, and users' exact needs probably not being met by the default implementation of anything.

**Comment by eldang** [comment]
Are you still recruiting?  I use Geopy a lot and find it very useful, and noticed this thread while trying to figure out why a couple of things (for which I see open PRs) aren't working.  I'd be happy to spend a day in the near future going through the current open PR list, and then commit to checking new/updated PRs about once a month.
