### ISSUE TITLE
Nose-cov win-64 bit incompatibility?

### ISSUE THREAD

**Issue by bmcguirk** [geopy/geopy#152]
Hi guys - 

Please excuse the n00bism here, but I can't quite get geopy to install via conda build. Root anaconda installation is 3.4.3, but I have a few environments running 2.7. Machine is Windows 7, 64-bit. I run `conda skeleton pypi geopy` then `conda build geopy` and I keep getting the same error. This is the last bit of output: 

```
Installed c:\anaconda3\envs\_build\lib\site-packages\geopy-1.11.0-py3.4.egg
Processing dependencies for geopy==1.11.0
Finished processing dependencies for geopy==1.11.0

C:\Anaconda3\conda-bld\work\geopy-1.11.0>if errorlevel 1 exit 1
found egg: C:\Anaconda3\envs\_build\Lib\site-packages\geopy-1.11.0-py3.4.egg
number of files: 4
Fixing permissions
Fixing permissions
BUILD END: geopy-1.11.0-py34_0
TEST START: geopy-1.11.0-py34_0
Fetching package metadata: ......
Error: No packages found in current win-64 channels matching: nose-cov
```

Interestingly, installing `nose-cov` separately via the same process does, in fact, work. 
Apologies if this is a simple misconfiguration.

**Comment by KostyaEsmukov** [comment]
We are about to drop `nose` in favor of `pytest` (#266), so I'm closing this.
