### ISSUE TITLE
Please document where to find key used to sign PyPI releases

### ISSUE THREAD

**Issue by eriol** [geopy/geopy#158]
Hello,
can you document where to find the key used to sign releases?
I searched RSA key ID C31C9705 on pgp.mit.edu and keys.gnupg.net but I was not able to find it.

Thanks!

**Comment by KostyaEsmukov** [comment]
I know this is a very old issue, which was probably addressed to ijl, but just FYI:

My GPG key fingerprint is `2D3B9C1712FF84F7`. I sign all git commits with it and Github places a green tick with this ID (which means that I've added this key to my Github profile).

This key is uploaded to keys.gnupg.net. PyPI releases are signed with the same key. Here is how a validity of a release can be checked:
```
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 2D3B9C1712FF84F7
$ gpg --verify geopy-1.12.0.tar.gz.asc
gpg: assuming signed data in 'geopy-1.12.0.tar.gz'
gpg: Signature made Tue 13 Mar 2018 12:49:44 PM MSK
gpg:                using RSA key BE3D633AB6792715ECF34D742D3B9C1712FF84F7
gpg: Good signature from "Kostya Esmukov <kostya@esmukov.ru>" [unknown]
...
```

Let me know if you need any further information.

**Comment by eriol** [comment]
@KostyaEsmukov many thanks for your reply! I asked because I wanted to check signature when importing a new release for the Debian package I maintain. Thanks again!

**Comment by eriol** [comment]
@KostyaEsmukov thanks for your hard work! Yes, sorry I was a bit busy lately but I have update the Debian package to 1.16[¹]. I'm not a Debian Developer yet so I sent a request for sponsorship to my usual sponsor: the updated package should be in Debian before the end of the week. :)

[¹] https://salsa.debian.org/python-team/modules/geopy

**Comment by KostyaEsmukov** [comment]
The key used to sign releases has been changed to `A18FE9F6F570D5B4E1E1853FAA7B5406547AF062`, see https://github.com/geopy/geopy/issues/463#issuecomment-756125724
