### ISSUE TITLE
Add Mapbox Geocoding API

### ISSUE THREAD

**Issue by perrygeo** [geopy/geopy#159]
https://www.mapbox.com/developers/api/geocoding/

**Comment by kythanh** [comment]
I also am looking for Mapbox Geocoding support.

**Comment by jqnatividad** [comment]
@perrygeo, @kythanh, are you up to creating a PR?

**Comment by kythanh** [comment]
@jqnatividad I no longer working on Geocoding with Mapbox now.

**Comment by williamhammond** [comment]
I gave this a shot here https://github.com/geopy/geopy/pull/323
