### ISSUE TITLE
Example for Google Maps API geocoder?

### ISSUE THREAD

**Issue by dpsspatial** [geopy/geopy#171]
Hi all,

Is there an example out there to show how to use the Google Maps API with geoPy? 

Great tool - finding pretty good results with Nomanatim... would like to see how Google stacks up for our student-level geocoding.

Thank you!!!

**Comment by iamthen0ise** [comment]
Not sure that this ticket must be reviewed as an Issue. Here i placed my simple usecase of Google Maps API via geopy for reverse geocoding — means get address from location provided.

```
from geopy.geocoders import GoogleV3

point = '51.523910, -0.158578' #here's famous Sherlock Holmes' museum lat & lng

geolocator = GoogleV3()
address = geolocator.reverse(point)
print address[0] # use other indexes if you want more or less detailed address scope.
```
i hope my example would help you

**Comment by hcenvirons** [comment]
I recently switched a script I wrote from Nomanatim to Google and the success rate was a lot higher.

One thing to note is that Google Maps currently has a per user geocoding limit of 2500/day if you are geocoding without an API key. See https://developers.google.com/maps/documentation/geocoding/usage-limits for more. 

If you get them an API key, the code would just be

```
from geopy.geocoders import Google V3

geolocator = GoogleV3(api_key="your_API_key")
```

**Comment by dpsspatial** [comment]
Here's the example I've finally figured out (from some far-reaching pages...) - and yes, I've switched to the Google geocoder as Nominatim is pretty sensitive to missing information, Google hammers through it no problem

```
from geopy import geocoders
g = geocoders.GoogleV3(api_key='apikeygoeshere')

#create an input address string
#you can also build this by reading from an input database and building a string

inputAddress = '175 5th Ave, New York,  NY' 

#do the geocode
location = g.geocode(inputAddress, timeout=10)

#some things you can get from the result
print(location.latitude, location.longitude)
print(location.raw)
print(location.address)
```

**Comment by Streich676** [comment]
import os
from geopy import geocoders
from geopy.geocoders import GoogleV3

API_KEY = os.getenv("GOOGLEAPI")
g = GoogleV3(api_key=API_KEY)

#Create empty list to store results
loc_coordinates = []
loc_address = []

for address in df.address:
    try:
        inputAddress = address 
        location = g.geocode(inputAddress, timeout=15)
        loc_coordinates.append((location.latitude, location.longitude))
        loc_address.append(inputAddress)
    except:
        print('Error, skipping address...')

#Concatonate the two lists together creating a dataframe of address and coordinates. 
df_geocodes = pd.DataFrame({'coordinate':loc_coordinates, 'address':loc_address})

**Comment by surenciodepalma** [comment]
@Streich676 how would you go about wrapping your code, the try/except loop, into a function?

**Comment by jonkislin** [comment]
This guide was a lifesaver. Thank you!
