### ISSUE TITLE
Google GeocoderQuotaExceeded, though API Console doesn't show exceeding usage

### ISSUE THREAD

**Issue by dpsspatial** [geopy/geopy#175]
Hi all,

Trying to geocode 55 records, and only getting 1/2way through before I get the error:

_geopy.exc.GeocoderQuotaExceeded: The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time._

Looking at my Google Developers Console, the API usage is nowhere near the limit (i'm only < 100 per day) and the requests / second aren't near the limit either.

Is there a middle man here that I can't see that is causing this error? Is GeoPy sending requests too fast?

Thanks!

**Comment by dpsspatial** [comment]
Seems to have resolved itself without any further issues or change to my code... strange!

**Comment by konradbachusz** [comment]
What is the quota limit?

I tried using GeoPy to identify the latitude and longitude of a number of addresses but now I get this error message:
`GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests`

**Comment by dpsspatial** [comment]
The Google API documentation has the quotas listed - I'd share a link but they all seem to be connected to my account. You'll have to dig around a bit.

**Comment by KostyaEsmukov** [comment]
For Google it's https://developers.google.com/maps/documentation/geocoding/usage-and-billing

**Comment by tclancy** [comment]
>Trying to geocode 55 records

Google does rate-limit to 50 requests per second, so that could cause the blocking.
