### ISSUE TITLE
What's the best way to fix the failing Travis build?

### ISSUE THREAD

**Issue by riordan** [geopy/geopy#176]
I'm looking to add support for another geocoding service to Geopy, but I'm kind of afraid to do it until the master project is passing its CI tests with Travis.

For me, It's that I want my PR to be accepted without a problem, and not passing all the tests is a surefire way to ensure my PR never gets merged.

But at the same time, I also love the Geopy project (been building tools with Geopy long before I started working on a geocoder project) and don't want to scare folks away from adopting it and instead toward more vendor-specific implementations.

So what's the best way forward?

**Comment by mtigas** [comment]
@jqnatividad Done. I noticed you had an invite to join the "Committer" team to get commit access to the repo (I think ijl sent it). Anyway, I re-sent it. I don’t remember how to make that happen, but once you accept you’ll also be able to weed through the PRs yourself.

**Comment by jqnatividad** [comment]
@mtigas thanks!  Will be sure to weed thru PRs judiciously. :)
