### ISSUE TITLE
geocoders.base.Geocoder._call_geocoder() does not sent HTTP headers breaking Nominatim usage

### ISSUE THREAD

**Issue by icemac** [geopy/geopy#185]
`osm.Nominatim` expects the `User-Agent` as HTTP header otherwise it returns a HTTP-403. But there is no way to get `_call_geocoder()` to send this header:
- `requester` is not set by `Nominatim.geocode`, so `urllib.urlopen` is used as requester. But if there is a requester only the `url` is sent but not the headers. See https://github.com/geopy/geopy/blob/master/geopy/geocoders/base.py#L122 and the following lines.
- I could hardly think of a use-case where `bool(requester)` is `False` but the requester is callable, I am not sure what the initial use-case was for the code. (#L143)

Locally I now use a `class` derived from `osm.Nominatim` which converts `url` to a `Request` (as in https://github.com/geopy/geopy/blob/master/geopy/geocoders/base.py#L137) before calling `_call_geocoder()` with this request object as url. As not knowing the use-case for the code in `_call_geocoder()` I do not feel empowered to write a pull-request to get this fixed in the library.

**Comment by icemac** [comment]
#184 seems to be a possible solution.

**Comment by xmedeko** [comment]
Nominatim has just started to block these wrong requests, so this issue has become urgent, see also #262.

**Comment by KostyaEsmukov** [comment]
This has been fixed in `1.12.0`. A bit longer explanation is here: https://github.com/geopy/geopy/issues/262#issuecomment-373901306

I'm closing this.
