### ISSUE TITLE
Error in vincenty destination function

### ISSUE THREAD

**Issue by hannosch** [geopy/geopy#186]
I've reviewed the code of the vincenty distance and destination function against the mathematical formulas cited on the Wikipedia page. From what I can tell there is one minor error in the destination function, which fails to do a power2 on one term.

Currently delta_sigma inside the loop (https://github.com/geopy/geopy/blob/master/geopy/distance.py#L482) is defined as:

```
delta_sigma = B * sin_sigma * (
    cos2_sigma_m + B / 4. * (
        cos_sigma * (
            -1 + 2 * cos2_sigma_m
        ) - B / 6. * cos2_sigma_m * (
            -3 + 4 * sin_sigma ** 2
        ) * (
            -3 + 4 * cos2_sigma_m ** 2
        )
    )
)
```

I believe the `-1 + 2 * cos2_sigma_m` part is missing a power 2 and should be `-1 + 2 * cos2_sigma_m ** 2` instead, so it all reads:

```
delta_sigma = B * sin_sigma * (
    cos2_sigma_m + B / 4. * (
        cos_sigma * (
            -1 + 2 * cos2_sigma_m ** 2
        ) - B / 6. * cos2_sigma_m * (
            -3 + 4 * sin_sigma ** 2
        ) * (
            -3 + 4 * cos2_sigma_m ** 2
        )
    )
)
```

**Comment by jqnatividad** [comment]
Hi @hannosch!  Can you create a PR?
