### ISSUE TITLE
Remove Yahoo Placefinder support as the service has been EOLed

### ISSUE THREAD

**Issue by jqnatividad** [geopy/geopy#190]
https://boss.yahoo.com/#EOL_MSG

**Comment by jqnatividad** [comment]
For now, will remove Yahoo API keys so at least Travis build doesn't fail.

**Comment by jqnatividad** [comment]
Will fully remove Yahoo Placefinder support in the upcoming 1.12 release cc @jhmaddox

**Comment by KostyaEsmukov** [comment]
The service indeed [looks discontinued][1]. For an alternative [they propose][2] to use their [search query language (YQL)][3] against `geo.places` table. I suppose that these two are not compatible, so it would be better to simply delete the Placefinder implementation without trying to migrate it to YQL. 

However what concerns me is that their Placefinder [API endpoint][4] seems to be working, though I can't verify it as they don't allow to register new apps now.

Anyway, according to their [BOSS FAQ][2], the service should be offline, so it seems to be OK to just remove this implementation completely.

[1]: https://developer.yahoo.com/boss/placefinder/#pricing
[2]: https://developer.yahoo.com/boss/#is-there-an-alternative-solution-for-geo-coding-services
[3]: https://developer.yahoo.com/yql/
[4]: https://yboss.yahooapis.com/geo/placefinder?location=1%20MainStreet
