### ISSUE TITLE
Add ability to use local Arcgis geocoder

### ISSUE THREAD

**Issue by jqnatividad** [geopy/geopy#192]
Instead of just the Arcgis World geocoder which is a paid service.

If your organization already has a Arcgis server with a geocoder optimized to your reqts, you should be able to use that.

**Comment by locontem** [comment]
I am also looking to be able to use my own arcgis locator hosted on my arcgis server. My main concern is location accuracy, our local locator has precise point address locations and so I would rather use this one instead of the world geocoder.

**Comment by KostyaEsmukov** [comment]
It would be better to do this on top of #227, which is not merged yet
