### ISSUE TITLE
Add ability to use a local instance of Mapzen Search

### ISSUE THREAD

**Issue by jqnatividad** [geopy/geopy#193]
Perhaps, this can be done by giving the ability to change the API endpoint?  I'm sure that Mapzen Search is more than just hosted Pelias, but can the current Mapzen Search geopy geocoder support this?  cc @migurski

**Comment by migurski** [comment]
Should be possible! I’ve [recently made it easier to install Pelias locally](http://mike.teczno.com/notes/openaddr/5min-geocoder.html) while [Pelias team has been doing the same](https://github.com/pelias/pelias-doc/blob/master/installing.md), so providing a configuration URL should be enough. I’ll work on another PR; unsure when.

**Comment by KostyaEsmukov** [comment]
Closing, this has already been done in ffedfb5. Also linking #258 where the discussion about possible Mapzen removal in the future releases takes place.
