### ISSUE TITLE
Make Location and Point classes pickleable

### ISSUE THREAD

**Issue by drdaeman** [geopy/geopy#195]
Currently, one can't easily pickle the Location and Point objects, e.g. for caching the results:

```
>>> pickle.dumps(loc)
...
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled
```

I'd suggest to implement `__getstate__` and `__setstate__` so the essential instances could be trivially preserved without need to think about their internals.

**Comment by KostyaEsmukov** [comment]
Resolved with 3479b0c...cc233b2.

However, Location might still sometimes be unpicklable, if its `raw` object is not picklable. But this looks like a rare edge case.
