### ISSUE TITLE
geopy.exc.GeocoderTimedOut: Service timed out

### ISSUE THREAD

**Issue by jvilaplana** [geopy/geopy#199]
I get an error when trying to get the coordinates of some locations:

```
python
>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim()
>>> location = geolocator.geocode("m u n d e l e i n i l")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/xxx/venv/lib/python2.7/site-packages/geopy/geocoders/osm.py", line 193, in ge
ocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/xxx/venv/lib/python2.7/site-packages/geopy/geocoders/base.py", line 170, in _
call_geocoder
    raise GeocoderTimedOut('Service timed out')
geopy.exc.GeocoderTimedOut: Service timed out
```

**Comment by gonzalolc** [comment]
that means you reached a "time out" in the nominatim server. initialize Nominatim with a higher timeout (>1)
try this:
`geolocator=Nominatim(timeout=3)`

**Comment by konradbachusz** [comment]
I increased the timeout to 3 or even 10 but I still get this error message

`GeocoderTimedOut: Service timed out`

**Comment by Khantanjil** [comment]
The error has to do with the **speed** of the connection with geopy. The error depends on whether the internet is **good or bad**. As I have a terrible internet, for me it resulted with the following object: 
`nom = ArcGIS (timeout = 10)`

**Comment by ShahidaPervin** [comment]
Hello, I am stuck with the following command and the same problem. It doesn't go anywhere. Anyone to help please? Thank you.

df['location'] = df['locaddress'].apply(geocode)

**Comment by KostyaEsmukov** [comment]
For Nominatim is usually helps to add RateLimiter: https://stackoverflow.com/a/51573613

Another option would be to switch from free Nominatim to a paid alternative, such as OpenMapQuest or PickPoint.
