### ISSUE TITLE
Vincenty destination function returns incorrect point

### ISSUE THREAD

**Issue by rukayaj** [geopy/geopy#200]
Possibly I am going crazy but it looks to me as if https://github.com/geopy/geopy/blob/master/geopy/distance.py#L527 is returning a point with the lat/long the wrong way round? It should be:

`return Point(units.degrees(radians=lng2), units.degrees(radians=lat2))`

or am i missing something?

**Comment by micahcochran** [comment]
The [docstring](https://github.com/geopy/geopy/blob/master/geopy/point.py#L48) in the Point class is a little inconsistent about the order, but [Point.__new__ function](https://github.com/geopy/geopy/blob/master/geopy/point.py#L106) has the latitude as first argument.

**Comment by KostyaEsmukov** [comment]
I'm closing this as docs have been fixed by #207
