### ISSUE TITLE
Mocking responses

### ISSUE THREAD

**Issue by medecau** [geopy/geopy#203]
> You may wonder: why not commit captured data and run mocked tests? Because there are copyright constraints on the data returned by services.
> [CONTRIBUTING.md](https://github.com/medecau/geopy/blob/e3b3fbef1cb61d4c81d9b505b56c5208018f153d/CONTRIBUTING.md)

IANAL but am quite confident that sample responses would fall under fair use.
Alternatively data can be faked as much as APIs.
There should be a solution for quick and easy testing both locally and on travis-ci.

There are currently 37 open issues. #34 is two years old and has no responses.
20 pull-requests open. Most did not pass the tests on travis-ci, have no responses, and are already months old.

**Comment by KostyaEsmukov** [comment]
@medecau would you mind if I keep this open?

I still believe this is a great idea, although I'm not quite sure yet how to implement it better than what we have now (and if it's even beneficial at all).

The recorded responses might get obsolete, so they need to be kept up to date somehow. Another issue is that API keys shouldn't get recorded, while [vcrpy](https://vcrpy.readthedocs.io/), for example, records all query params and headers by default.

The reasoning given in CONTRIBUTING.md (cited above) is valid for just some of the providers, the others' responses might still be mocked.

On the other hand, mocked responses would significantly speed up the testing pipelines and make them more stable, and would make local development easier (by not requiring a bunch of api keys for each provider).

**Comment by KostyaEsmukov** [comment]
Closing this in favor of #413
