### ISSUE TITLE
geocoder.us

### ISSUE THREAD

**Issue by eruci** [geopy/geopy#220]
geocoder.us is no longer active. yet, some alternatives exist, tiger geocoder, geocoder.ca, geocode.xyz, but are not integrated.

**Comment by KostyaEsmukov** [comment]
`geocoder.us` hostname doesn't resolve, though the site (and, I guess, the service) is reachable by ip: http://206.220.230.164/ . The implementation relies on hostname, so it must be broken now.

> yet, some alternatives exist, tiger geocoder, geocoder.ca, geocode.xyz, but are not integrated.

They seem to have completely different APIs.

I think we should consider removing this code.

**Comment by eruci** [comment]
Let me know if you need any help with integrating geocode.xyz. There are 4 output options to chose from (XML,CSV, JSON and JSONp)

**Comment by KostyaEsmukov** [comment]
I wouldn't do that by myself, but would be happy to accept a PR of someone with any of these other services implementations. If you're willing to have geocode.xyz implementation included to geopy, please consider opening a PR. :)

**Comment by KostyaEsmukov** [comment]
Removed GeocoderDotUS class in #286
