### ISSUE TITLE
ArcGIS: specify output fields

### ISSUE THREAD

**Issue by diogocp** [geopy/geopy#225]
ArcGIS geocoding requests do not return the country code by default, which I need for my application. It should be possible to pass a parameter to the geocode method to specify the output fields.

Relevant API documentation: https://developers.arcgis.com/rest/geocode/api-reference/geocoding-find-address-candidates.htm#ESRI_SECTION1_72748BA0A3B94DE2B5C3C38F56D2D026

**Comment by jmb** [comment]
I've not tested this, but have you tried adding the parameter into the query string? i.e. put `&outFields=Country` after your search string. Then you could dig it out of the raw data in the returned Location object.

That said, I've just noticed that the `find` operation has been deprecated and has been replaced with `findAddressCandidates`, so this module needs updating.

**Comment by diogocp** [comment]
It doesn't work because query string gets urlencoded.

**Comment by jmb** [comment]
Actually, having just updated the code for the latest API in my pull request #227, this idea won't work due to the urlencode function.

For a reverse lookup you can get it from the raw data in the `Location` object:  `result.raw['CountryCode']` (where result is the output from calling the `reverse` function).

**Comment by jmb** [comment]
Ok, I've worked this out for you - I can add a parameter to the geocode function to specify the outFields. However, do you think you should pass a string: `out_fields="Country,Type"` or a list/tuple: `out_fields=("Country","Type")`. I'm not sure which form or parameter would be best. At the moment I've gone with the list/tuple option - I will update my PR in a moment.

**Comment by jmb** [comment]
If you want to test the string option with my [arcgis-api-update](https://github.com/jmb/geopy/tree/arcgis-api-update) branch that would be great. 

I'll look into updating it to accept both.

**Comment by diogocp** [comment]
Thanks for the PR. I have done some quick tests and it looks ok.

**Comment by jmb** [comment]
It now takes either a string (`,`-delimited if more than one field requested) or a list/tuple. I have also added a couple of tests - hopefully these are acceptable to the maintainers! (I'm pretty new to using tests).

**Comment by KostyaEsmukov** [comment]
Resolved by #287
