### ISSUE TITLE
vincenty vs geoqueryset

### ISSUE THREAD

**Issue by kodeine** [geopy/geopy#230]
so i'm trying to calculate distance using vincenty i get the value of 7.5km but the same distance using geoqueryset is 10.6km. Any ideas?

Do i need to change ellipsoid? The srid on geo query set is 4326 and vincenty by default uses WGS-84 as well which seems correct for google maps. So i'm not sure why the difference in distance calculations.

**Comment by KostyaEsmukov** [comment]
Any example? I cannot do anything unless there's a reproducible example.

Also vincenty is deprecated since 1.13 (see #144), which is replaced with a more accurate `geodesic` algorithm. Perhaps that might have fixed the issue?..

Closing, but feel free to reopen if there's an example.
