### ISSUE TITLE
How to get value postalcode or zipcode?

### ISSUE THREAD

**Issue by ibnbay99** [geopy/geopy#232]
How i can get value postalcode or zipcode?
For example using Google API?

Thanks/....

**Comment by ddofer** [comment]
Joining the question: I want to get the zipcode of a USA location (given address or latlong).

**Comment by eldang** [comment]
Some pointers here: the GoogleV3 geocoder returns some additional information as `location.raw["address_components"]`.  That in turn is a series of objects each with a few attributes:

* `types` tells you which address part Google's geocoder thinks it is.  For a US ZIP code, the main 5-digit part has a `type` of `postal_code` and the optional 4 digits for added precision have the `type` `postal_code_suffix`.
* `long_name` and `short_name` are both the actual address part - for ZIP codes they seem to be identical.

**Comment by KostyaEsmukov** [comment]
Location class doesn't define a specific field for zipcode, but some geocoder services return that data which can be retrieved from the `raw` field:

```py
>>> from geopy.geocoders import Nominatim
>>> geolocator = Nominatim(user_agent="specify_your_app_name_here")

>>> location = geolocator.geocode("gum moscow", addressdetails=True)
>>> location.raw['address']['postcode']
'109012'
```

@eldang also mentioned above that GoogleV3 supports that as well in a similar manner.
