### ISSUE TITLE
Unit conversion error

### ISSUE THREAD

**Issue by rosenbaum** [geopy/geopy#234]
units.kilometers does not handle the feet argument properly, the issue is specifically with line 64:

> miles += feet / ft(1.)

followed by line 67:

> ret += miles * 1.609344

feet/ft(1.) is of course the number of kilometers, not miles.  So running the following test:

> Distance(feet=1).feet

1.609344

This can be fixed by changing line 64 to:

> miles += feet / ft(miles=1.)

**Comment by KostyaEsmukov** [comment]
Fixed by #162
