### ISSUE TITLE
Error using geopy and Google AppEngine

### ISSUE THREAD

**Issue by armandomiani** [geopy/geopy#237]
As an AppEngine uses urlfetch module, the validate_certificate defaults option is False, so I receive the message below:

```
File "/home/miani/hobsdev/hobs.api/controllers/admin.py", line 36, in test_geo
    location = geocoder.reverse("52.509669, 13.376294")
  File "/home/miani/hobsdev/hobs.api/lib/geopy/geocoders/googlev3.py", line 266, in reverse
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "/home/miani/hobsdev/hobs.api/lib/geopy/geocoders/base.py", line 171, in _call_geocoder
    raise GeocoderServiceError(message)
GeocoderServiceError: Invalid and/or missing SSL certificate for URL: https://maps.googleapis.com/maps/api/geocode/json?latlng=52.509669%2C+13.376294&sensor=false

```

Maybe the solution is providing an option to Geocoder where the developer is able for setting the certificate validation true or false. 

Best,

@armandomiani

**Comment by KostyaEsmukov** [comment]
#291 has added support for passing custom `ssl_context`, which might be helpful there. For example, a custom CA bundle can be specified, or TLS verification can be disabled completely.

I don't know whether this is still an issue (maybe it's already fixed on GAE side), or if the GAE's `urlfetch` library respects the urllib's `context`, so I would like someone to check this out. I'm keeping this issue open until then.

**Comment by KostyaEsmukov** [comment]
Closing. I assume this is no longer an issue or just nobody cares about this specific scenario.
