### ISSUE TITLE
Handling no place return from IGN

### ISSUE THREAD

**Issue by gvatin** [geopy/geopy#244]
There is no Exception handler for managing the case when geocoder such as IGN (for french geocoding) sends no place. So the places[0] return an error during the execution. It would be great to manage these cases !

**Comment by KostyaEsmukov** [comment]
The current convention is to return `None` for an empty response, which is [specified in docs](http://geopy.readthedocs.io/en/1.12.0/#module-geopy.geocoders). If an exception is being thrown – then this is a bug. PRs are welcome.
