### ISSUE TITLE
UnboundLocalError: local variable 'cos_sq_alpha' referenced before assignment

### ISSUE THREAD

**Issue by 1kastner** [geopy/geopy#245]
First of all thanks for the great contribution! Most of the times the library serves well, but recently I started to get the following kinds of errors:

    Traceback (most recent call last):
      ...
      File "evaluate_all_methods.py", line 226, in score_algorithm
        point = geopy.Point(lat, lon)
      File "...\lib\site-packages\geopy\distance.py", line 322, in __init__
        super(vincenty, self).__init__(*args, **kwargs)
      File "...\lib\site-packages\geopy\distance.py", line 115, in __init__
        kilometers += self.measure(a, b)
      File "...\lib\site-packages\geopy\distance.py", line 414, in measure
        u_sq = cos_sq_alpha * (major ** 2 - minor ** 2) / minor ** 2
    UnboundLocalError: local variable 'cos_sq_alpha' referenced before assignment

My code is quite complex and it happens here and then while processing bulk requests. Because of that I can not easily break it down to the place where it fails.

**Comment by 1kastner** [comment]
One thing I found in the code: when the distance is too short, the while-loop is never entered so that cos_sq_alpha is not set. Especially the algorithm does not handle np.nan values well.

**Comment by 1kastner** [comment]
I would suggest a check of the variables before the distance is calculated. As a numpy import for checking for NaNs would be an overkill, maybe a smaller and greater zero can be checked, like:

    is_nan = lambda x: not (x > 0 or x < 0)

That way the library will turn more user friendly.

**Comment by KostyaEsmukov** [comment]
Should be fixed by 15ebe15. Feel free to reopen if the problem persists.

Also linking #144 which actually contained the fix (but without tests).

**Comment by KostyaEsmukov** [comment]
@1kastner I like the input checking suggestion. I'd gladly accept a PR that does this.

**Comment by KostyaEsmukov** [comment]
#272 would introduce some input validation
