### ISSUE TITLE
Pulling wrong cordinates for IATA airport codes

### ISSUE THREAD

**Issue by Nvironmental** [geopy/geopy#249]
No longer pulls right lat long and address for given IATA code was working smooth as butter earlier

**Comment by micahcochran** [comment]
I don't actually understand this issue.  @Nvironmental Could you provide an example of code that was working that is no longer working?

**Comment by KostyaEsmukov** [comment]
That must have been an issue with a concrete geocoding provider. Doesn't seem to be geopy-related to me, so I'm closing this.
