### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by freyfogle** [geopy/geopy#251]
Hi,

I have found several bug with this code, specifically around the implementation of the opencage geocoder. I'm happy to put in time on fixing them and submit pull requests, but am concerned that this project seems unmaintained. 

The README says "build: failing" which isn't a good sign, there are 59 issues and 31 pull requests sitting open, last commit September 2016.

Please let me know. Many thanks!

**Comment by jmb** [comment]
It seems not! :(

**Comment by jmb** [comment]
I just found this project https://github.com/DenisCarriere/geocoder which might be worth moving over to as it seems to be actively maintained.

**Comment by hugovk** [comment]
And by the way, pypinfo tells me geopy has been downloaded 265,639 times last month from PyPI! That's compared to 50,953 for geocoder.

**Comment by jmb** [comment]
I have now had a response and will hopefully be able to help sorting this project out a little, but it will take me some time as I'm not actively using it at the moment. Hopefully little by little we can get it back in order and up to date!

**Comment by jmb** [comment]
@KostyaEsmukov is also onboard I believe and looks to be actively sorting out a next-master branch.

**Comment by KostyaEsmukov** [comment]
Hi guys, I've been given permissions to be the new maintainer there just yesterday and I already started doing the housekeeping job (in the [next-master](https://github.com/geopy/geopy/tree/next-master) branch, as @jmb noted), so you can expect some changes quite soon. I'll make a PyPI release in a couple of days.

Thank you @jmb for taking the initiative there, I'll get in touch with you (in a week or even less) over email after that release to better coordinate our efforts.

**Comment by freyfogle** [comment]
that's great news @KostyaEsmukov  Will get my pull request in shortly! Am closing this thread

**Comment by KostyaEsmukov** [comment]
Just want to let you know that 1.12.0 has been released yesterday 🎉

**Comment by freyfogle** [comment]
Great work @KostyaEsmukov 
I look for to many more releases in near future. 

Thanks for all your efforts
