### ISSUE TITLE
GeocoderServiceError: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by RivieraData** [geopy/geopy#253]
Hi,

Thank you for you amazing job.

Can you please tell us how many requests can we do per minutes?

Thank you

**Comment by eldang** [comment]
That depends on the individual geocoding service, not on this Python module. Most of them put information about their rate limits in the documentation, and for some you can raise the limit by creating an account and paying for the premium service.

The answer you need will depend on which geocoder you are using.  As an example, here's the page for Google's: https://developers.google.com/maps/documentation/geocoding/usage-limits

**Comment by KostyaEsmukov** [comment]
Closing in favor of #268

**Comment by KostyaEsmukov** [comment]
geopy since 1.16.0 includes a `RateLimiter` class which provides a convenient way to overcome the issue. 

- Docs: https://geopy.readthedocs.io/en/1.16.0/#usage-with-pandas
- PR: #317
