### ISSUE TITLE
When I use the latitude and longitude conversion address, there is an error after the conversion address

### ISSUE THREAD

**Issue by zp672087110** [geopy/geopy#254]
Hi,

Thank you for you amazing job.

i have some error !  can you help me?

Thank you

#this is my code

from geopy.geocoders import Nominatim 
geolocator = Nominatim() 

a=("36.1643410000,114.3345950000")

loc=location.raw[u"address"]
##['西光录村', '安阳县', '邯鄲市', '河南省', '中国']
ps :In Henan Province, China, there is no Handan City, Handan City belongs to Hebei Province

**Comment by eldang** [comment]
Hello!
This sounds like it's an error in the underlying data that Nomatim uses, not in this project.  For context: all that geopy does is provide an interface between your script and an external geocoder, and it has no control over those geocoders' data.  Nomatim is OpenStreetMap's geocoder, so you can look at its data directly like this:

http://nominatim.openstreetmap.org/search.php?q=36.1643410000%2C114.3345950000&polygon_geojson=1&viewbox=

Personally I find that OpenStreetMap's data quality varies a lot from place to place.  For your situation I recommend trying a different geocoder out of the several that Geopy can connect to.

**Comment by zp672087110** [comment]
thanks a lot
