### ISSUE TITLE
Is Mapzen still supported?

### ISSUE THREAD

**Issue by dpsspatial** [geopy/geopy#258]
All,

Trying to use GeoPy with Mapzen in a script I had set up last year and it doesn't seem supported. Has something changed? 

Thanks!

**Comment by micahcochran** [comment]
[Mapzen is shutting down](https://mapzen.com/blog/shutdown/).  So, this issue is a moot point.  :frowning_face:

**Comment by KostyaEsmukov** [comment]
Implementation for Mapzen has been added in #183, but it hasn't been released to PyPI yet. And while it was there, Mapzen has shut down their API `¯\_(ツ)_/¯`.

I've added support for custom domains in ffedfb5 (just in case someone is willing to use it with a custom Mapzen-alike provider) and a warning in the docs that this geocoder might be removed soon. 

So I'm still adding it to the upcoming 1.12.0 release, but I can't promise that it will stay there for long (unless there's a demand from community like you guys).

Please let me know if you think that Mapzen geocoder should stay. Thanks.

**Comment by migurski** [comment]
Mapzen’s gone, this code should be removed as well.

**Comment by dpsspatial** [comment]
I would advocate that this code be ported over to consume the Geocode.earth API, which is the new implementation of the Pelias geocoder - or any self-hosted instance of Pelias...

**Comment by jqnatividad** [comment]
cc @orangejulius

**Comment by orangejulius** [comment]
Hi all! Yes [Pelias](https://pelias.io) is definitely alive and well. The support for custom domains should allow anyone using the Pelias geocoder (which is the underlying project that powered Mapzen Search for geocoding) to customize it.

Making geocode.earth the default URL would definitely be appreciated, although there are other hosted Pelias offerings, and lots of people using self-hosted Pelias.

As core maintainers of Pelias and the owners of geocode.earth, which is a paid service, I don't really want to be the one making the decision on what the default domain (if any) is, but I'll support any decision you all make :)

**Comment by KostyaEsmukov** [comment]
Thanks for chiming in!

In this case, I think, it makes sense to rename the `Mapzen` class to `Pelias`, just to avoid confusion. I'm absolutely fine with having geocode.earth as default URL.

However, what's bothering me is having a geocoding service to test this implementation against in Travis CI. geocode.earth doesn't seem to provide free API keys. Is there any chance geopy could get one for free, exclusively for testing purposes?

**Comment by orangejulius** [comment]
Hey @KostyaEsmukov,
I just sent a key that you can use for testing to the email listed on your GitHub account. Let me know if you have any questions!

**Comment by KostyaEsmukov** [comment]
Opened #309 PR, where Mapzen is renamed to Pelias and GeocodeEarth is added as a separate geocoder. 

I decided to have `domain` a required argument in Pelias and introduce GeocodeEarth separately, because it looks cleaner to me and also allows to customize GeocodeEarth while keeping Pelias more flexible (e.g. self-hosted Pelias might not require an api_key, while GeocodeEarth requires one).

**Comment by dpsspatial** [comment]
Thank you all for your feedback and help with this!

**Comment by KostyaEsmukov** [comment]
#309 has been merged and will be released in `1.15.0`.
