### ISSUE TITLE
Nominatim: view_box parameter for Nominatim instance only works with string-represented numerical tuple

### ISSUE THREAD

**Issue by tsaomao** [geopy/geopy#261]
Hi and thanks for all your collective work on geopy. Really appreciate it and super helpful for data analytics! 

(Note, as an aside, that it's a little weird that the tuple is (longitude1, latitude1, longitude2, latitude2) instead of leading each 2-element pair within the 4-element tuple with latitude, but that seems to be [Nominatim's convention](https://github.com/openstreetmap/Nominatim/blob/81a7ea36db7d3b055acf25a36d2ea2c27af74765/test/bdd/api/search/params.feature), so it makes sense to keep it that way for the Class's parameters in geopy too - so that's not what this issue is about.)

Anyhow, the view_box parameter is a 4-element tuple of positive or negative integer or floating point data defining opposite corners of a rectangle in a 4-element python tuple(). If you use numerical data to create the tuple, you receive an error:

Setup and Call: 
```
box_tuple = tuple([180, 22, -180, -22])
geolocator = Nominatim(view_box=box_tuple)
location2 = geolocator.geocode("Peru")
```
 
Error:
```
~/anaconda3/lib/python3.6/site-packages/geopy/geocoders/osm.py in geocode(self, query, exactly_one, timeout, addressdetails, language, geometry)
    161         # `viewbox` apparently replaces `view_box`
    162         if self.view_box:
--> 163             params['viewbox'] = ','.join(self.view_box)
    164 
    165         if self.country_bias:

TypeError: sequence item 0: expected str instance, int found
```

If you use string data to create the tuple, no error, and the call to geocode() works as expected, resulting in a location returned that lies within the defined boundaries.

Setup and Call: 
```
box_tuple = tuple(["180", "22", "-180", "-22"])
geolocator = Nominatim(view_box=box_tuple)
location2 = geolocator.geocode("Peru")
location2
```

Output:
`Location(Perú, (-6.8699697, -75.0458515, 0.0))`

FWIW, my suggested fix would be to convert a numerical tuple to strings somehow, but I am not sure what the most efficient implementation or input handling would be, which is why I'm submitting this as an issue instead of coding an implementation.

I'm using geopy 1.11.0 with a Python 3.6.2 in a jupyter notebook.

Please let me know if I've been unclear or you need more info or have other questions. Thanks again, so much for all your work on this.

**Comment by KostyaEsmukov** [comment]
Thanks for reporting this.
I'd suggest to do the following:
1. Simply replace `','.join(self.view_box)` [line](https://github.com/geopy/geopy/blob/82cdf7e3d971c3310c2d5373c9e3fb156a1d86eb/geopy/geocoders/osm.py#L199) with `','.join(str(coord) for coord in self.view_box)`
2. Allow the `view_box` to be in the following form: `[Point(22, 180), Point(-22, -180)]`. I guess it would be more natural to geopy users than forcing to use the Nominatim's convention.
3. Document this and add some tests.

Please let me know if you're still interested in providing a PR! Don't worry if points 2 and 3 are not clear: I'd be happy to help.
