### ISSUE TITLE
I get OVER_QUERY_LIMIT occasionally

### ISSUE THREAD

**Issue by ravitdx** [geopy/geopy#270]
Hi,

I am using google to get locations and places. we used your library to do that. It works fine. But occasionally we get `The given key has gone over the requests limit in the 24 hour period or has submitted too many requests in too short a period of time.` for no reason. when we use 

> https://maps.googleapis.com/maps/api/geocode/json?address=San+Francisco&key=XXXXXXXXXX

it works perfectly everytime. please help use out. thanks

**Comment by KostyaEsmukov** [comment]
That's written in [the doc](http://geopy.readthedocs.io/en/1.12.0/#geopy.geocoders.GoogleV3.__init__).

```
geolocator = GoogleV3(api_key='XXXXXXXXXX')
location = geolocator.geocode('San Francisco')
```

**Comment by umbe1987** [comment]
I think things are going to change.
https://developers.google.com/maps/documentation/geocoding/usage-and-billing

**Comment by KostyaEsmukov** [comment]
Thanks for the reminder! So far it still works w/o API keys, but I'll keep my eye on this and will add a `ConfigurationError` exception once they disable keyless access completely.

**Comment by KostyaEsmukov** [comment]
Added a deprecation warning in bab4e32ef0407d650bf6c072bdf18551241dd120 for GoogleV3 usage without an API key.
