### ISSUE TITLE
Address input format

### ISSUE THREAD

**Issue by m4chi** [geopy/geopy#271]
Hi, Thanks for the great module. I am relatively new to all this but tried your module with Japanese addresses (in Japanese and English), which yields some results but not precise ones. I'd like to make sure that this is not due to my mistaken input. Is there any recommended format for entering addresses in Japan / in Japanese?

My example is this address of SEGA Holdings Japan:
〒140-8583 東京都品川区東品川1-39-9
1-39-9 Higashi-Shinagawa, Shinagawa-ku, Tokyo 140-8583

When using the English version, it does recognize the address to the "Shinagawa-ku" level, but not further.

**Comment by KostyaEsmukov** [comment]
geopy is just a wrapper for other geocoding services. For results accuracy you should consult with the actual geocoding service you're querying. 

Closing, as this is not an issue with geopy itself.

But if you specify (just reply with a comment here) which service you are actually using, I might try to give you some hints.
