### ISSUE TITLE
Add MaxMind GeoLite db?

### ISSUE THREAD

**Issue by dangayle** [geopy/geopy#274]
Would it be possible to add the MaxMind GeoLite db as a backup/alternate solution in addition to the web-based GeoIP lookups?

**Comment by KostyaEsmukov** [comment]
Although it would be a simple proxy to another package (`geoip2`? as an optional dependency), I think it makes sense to provide such geocoder class with an interface similar to the others. Reverse geocoding would not be implemented, of course.

But are there any geocoders in geopy which support online lookup for IP addresses? I know about maxmind API service, but it's not currently implemented in geopy. In that case it would be nice to have both implemented (as two different geocoder classes).

**Comment by dangayle** [comment]
Oh, ha ha. Didn't even think that Geopy didn't do IP lookups.

**Comment by KostyaEsmukov** [comment]
On the second thought I think there's no point in having it in geopy. geoip works specifically with IP addresses, while geocoders work with points of interest. These two applications are different.

I'm closing this, and I would suggest to use other libraries for working with geoip instead.
