### ISSUE TITLE
Problem with view_box parameter in Nomination (OSM)

### ISSUE THREAD

**Issue by senjed** [geopy/geopy#307]
I used Nomination for geocoding and included the view_box parameter but still the results of the geocoding are not inside the view box.

**Comment by senjed** [comment]
So say I want to get all the Krogers lat longs inside a bounding box:
` bb = tuple(["39.808631", "-83.2102799", "40.1572719","-82.7713781"])
  geolocator = Nominatim(view_box=bb)
  query = "Kroger"
  results = geolocator.geocode(query=query ,exactly_one=False, limit=None,language='En')
  for result in results:
        print result.latitude , result.longitude
`
but the results I get are outside of the veiw_box. I was wondering if view_box matters at all without including bounded=True?

**Comment by KostyaEsmukov** [comment]
> I was wondering if view_box matters at all without including bounded=True?

Yep, it does, for some queries. See [test_view_box][test_view_box] for example. `view_box` without `bounded=True` is just a hint to the service, which might be ignored.

`bounded` param support has just been added in #182 (as you have already discovered 😉).

The following command can be used for now to install the development version of geopy containing the `bounded` param:

    pip install --upgrade https://github.com/geopy/geopy/archive/master.zip

[test_view_box]: https://github.com/geopy/geopy/blob/e67a5bf389a5d7d99f3bf5e5a5aa1fdc011e22c3/test/geocoders/nominatim.py#L172

**Comment by senjed** [comment]
thank you so much!

**Comment by KostyaEsmukov** [comment]
I assume this can be closed. Feel free to reopen if this is still an issue.
