### ISSUE TITLE
Nominatim geopy.exc.GeocoderInsufficientPrivileges: HTTP Error 403: Forbidden with default user-agent

### ISSUE THREAD

**Issue by xmedeko** [geopy/geopy#314]
When using default user-agent: `geopy/x.y` the Nominatim service returns 403: `geopy.exc.GeocoderInsufficientPrivileges: HTTP Error 403: Forbidden`. Setting a custom user-agent fixes the issue.

Seems someone is bombing the osm with geopy. What about to make the `user_agent` argument compulsory, so everyone has to make own `user-agent`? Or it should be mentioned in the docs to set it up always, at least.

See also #262

**Comment by KostyaEsmukov** [comment]
> Seems someone is bombing the osm with geopy.

Hopefully this is a temporary issue.

> What about to make the user_agent argument compulsory, so everyone has to make own user-agent?

I would prefer to not make the `user_agent` param required unless the default one would become banned permanently on the Nominatim side. The reason for that is quite pragmatical: there're a lot of code examples and harmless tiny scripts around the Internet which use the default `user_agent`. Breaking all of that doesn't seem right to me, as long as the default value still works.

However, we could add a warning to the Nominatim initializer, showing when the `user_agent` is the default one. (as if someone reads these warnings 🙃).

> Or it should be mentioned in the docs to set it up always, at least.

It is mentioned in the docs (though as a recommendation, not as a mandatory action). See the orange "attention" block in the Nominatim class doc: https://geopy.readthedocs.io/en/1.15.0/#geopy.geocoders.Nominatim

PS. See also #112

**Comment by xmedeko** [comment]
Ah, I see the nice orange "Attention" in the doc. Yep, the warning in the Nominatim could do the job, I read these warnings :-)

Also the README.rst should have some code like:
```py
geolocator = Nominatim(user-agent='my_app/0,1') # provide your user-agent, see doc ...
```
Note: the example does not work now.

**Comment by medvednic** [comment]
even after setting a custom user agent I get - `ConnectionRefusedError: [Errno 61] Connection refused
`

**Comment by xmedeko** [comment]
This issue is about HTTP 403 error. I have Nominatim with custom user-agent working fine (just checked now).  Try it again, if it fails, try it from different network and check your connection to the osm domain server `nominatim.openstreetmap.org`.

**Comment by KostyaEsmukov** [comment]
@xmedeko Yeah, I think it's reasonable to add the warning. 

As for adding the `user_agent` param to examples, I'm thinking about simply replacing Nominatim with some other geocoder instead, which works "out of the box" without any extra configuration. User-agent or api key params are cluttering the currently lightweight examples, which might give a false sensation that these parameters (i.e. an `api_key` or a `user_agent`) are required by all geocoders, while actually it's not the case.

I'll try to get to this by this weekend, probably along with #315.

**Comment by Developer-Felix** [comment]
0

"GeocoderInsufficientPrivileges" error - try to use 'Photon' instead of 'Nominatim'

from geopy.geocoders import Photon
geolocator = Photon(user_agent="measurements")

**Comment by PlusPlusMan** [comment]
Nominatim(user_agent="my_agent_ver1")

returns:
geopy.exc.GeocoderInsufficientPrivileges: Non-successful status code 403

Yesterday everything was working fine. Today, when I try anything for user_agent i get the same return
