### ISSUE TITLE
support for Geonames reverse findNearby in addition to findNearbyPlaceName

### ISSUE THREAD

**Issue by biokomiker** [geopy/geopy#326]
Geonames reverse supports two variants:

http://api.geonames.org/ **findNearby** ?lat=46.4964&lng=9.28403&username=demo

<geonames><geoname><toponymName>Pizzo Tambo</toponymName><name>Pizzo Tambo</name><lat>46.49703</lat><lng>9.2834</lng><geonameId>2658429</geonameId><countryCode>CH</countryCode><countryName>Switzerland</countryName><fcl>T</fcl><fcode>PK</fcode><distance>0.08547</distance></geoname></geonames>

http://api.geonames.org/ **findNearbyPlaceName** ?lat=46.4964&lng=9.28403&username=demo

<name>Montespluga</name>

The output differs the first one being more useful for reverse tagging pictures, the second one being implemented in geopy.

I suggest to add some code in order to be also able to make the findNearby searches via geopy. It just requires some minor changes in geonames.py and defaults to the old behaviour.

Greetings !

```
    reverse_path = '/findNearbyPlaceNameJSON'
    # add findNearby
    findNearby_path = '/findNearbyJSON'
```

        self.api_reverse = (
            "%s://%s%s" % (self.scheme, domain, self.reverse_path)
        )
        self.api_reverse_findNearby = (
            "%s://%s%s" % (self.scheme, domain, self.findNearby_path)         
        )  # added to allow search findNearby

    def reverse(
            self,
            query,
            exactly_one=DEFAULT_SENTINEL,
            timeout=DEFAULT_SENTINEL,
            find_nearby_type='findNearbyPlaceName',      # added to allow search findNearby
    ):

        if find_nearby_type=='findNearby':  # added to allow search findNearby
            url = "?".join((self.api_reverse_findNearby, urlencode(params)))
        else:
            url = "?".join((self.api_reverse, urlencode(params)))
        logger.debug("%s.reverse: %s", self.__class__.__name__, url)
        return self._parse_json(
            self._call_geocoder(url, timeout=timeout),
            exactly_one
        )
```
```

**Comment by KostyaEsmukov** [comment]
Support for `findNearby` has been added in #327 and ae1d6c493.
