### ISSUE TITLE
Accuracy/ confidence score for geocoded values?

### ISSUE THREAD

**Issue by hwsamuel** [geopy/geopy#328]
When GeoPy's geocoders convert a string to an actual location, is there a way to get the accuracy/confidence with the conversion? For example, I'd like to compare the accuracy associated with geocoding "London England UK" vs geocoding "London" (which may mean Canada or UK). 

PS - I'm using Nominatim as my geocoder

**Comment by hwsamuel** [comment]
This is resolved. There is the `importance` field under `raw`, available in the results. This is used by Nominatim to rank their search, documented [here](https://wiki.openstreetmap.org/wiki/Nominatim/Development_overview#Wikipedia). Sample code below.

```
geolocator = Nominatim(user_agent="redacted")
location = geolocator.geocode("London")
print (location.raw['importance'])
```

**Comment by KostyaEsmukov** [comment]
Yeah, and that is a service-specific attribute. I don't think there's a generic answer to your question.

**Comment by jthomas992** [comment]
@hwsamuel @KostyaEsmukov  Should it not increase the accuracy score if the address is more granular?

For example:
[geolocator = Nominatim(user_agent="redacted")
location = geolocator.geocode("London")
print (location.raw['importance'])](url)
**returns 0.975489576540198**

But if I give a specific street address like below, it returns a very confidence  score ironically.

from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="redacted")
location = geolocator.geocode("21236 Birchwood Loop, 99567, AK,USA")
print (location.raw['importance'])
**returns 0.41000000000000003**

Am I interpreting it wrong or is there a better way to do this if I have street name,city,zip,country and want to find how accurate the geocode I retreive could be based on the address I have at such a granular level?

**Comment by KostyaEsmukov** [comment]
@jthomas992 geopy has nothing to do with the data which geocoding providers return, so your question should be asked to the Nominatim community, see https://wiki.openstreetmap.org/wiki/Nominatim/FAQ#How_should_I_report_problems.3F
