### ISSUE TITLE
GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests

### ISSUE THREAD

**Issue by konradbachusz** [geopy/geopy#330]
Hello,

What is the quota limit?

I tried using GeoPy to identify the latitude and longitude of a number of addresses. 

Example:

```
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="specify_your_app_name_here")
location = geolocator.geocode("175 5th Avenue NYC")
print(location.address)
print((location.latitude, location.longitude))
```

I get this error message:

`GeocoderQuotaExceeded: HTTP Error 429: Too Many Requests`

**Comment by KostyaEsmukov** [comment]
You should refer to the ToS of the specific geocoding service you use. 

The issue tracker is not a correct venue for usage questions (especially those which can easily be found on the Internet).

- https://operations.osmfoundation.org/policies/nominatim/
- https://stackoverflow.com/questions/49640197/error-429-too-many-requests-while-geocoding-with-geopy-in-python
- https://geopy.readthedocs.io/en/stable/#usage-with-pandas
