### ISSUE TITLE
Docs incorrectly refer to geopy.geocoders.options.default_ssl_context

### ISSUE THREAD

**Issue by robmarkcole** [geopy/geopy#331]
For example [below](https://geopy.readthedocs.io/en/stable/index.html?highlight=ssl#), but should be `geopy.geocoders.base.default_ssl_context`

![image](https://user-images.githubusercontent.com/11855322/47804766-8b971000-dd2d-11e8-961a-89698ca7102f.png)

**Comment by KostyaEsmukov** [comment]
Could you elaborate?

`geopy.geocoders.base.default_ssl_context` is definitely a non-existing reference: `default_ssl_context` is an attribute of `geopy.geocoders.base.options` [1], which is also exported as `geopy.geocoders.options` [2]. I don't see any issues in the attached screenshot.

\[1\]: https://github.com/geopy/geopy/blob/1ea494408f6d038bad67560b94ddce693b5ee849/geopy/geocoders/base.py#L168
\[2\]: https://github.com/geopy/geopy/blob/1ea494408f6d038bad67560b94ddce693b5ee849/geopy/geocoders/__init__.py#L142

**Comment by tobiz** [comment]
If I run this code on Kubuntu 18.04 (under Eclipse Version: 2018-09 (4.9.0) Build id: 20180917-1800) I get no problem.

import ssl
import certifi
def set_ssl_context():
    ctx = ssl.create_default_context(cafile=certifi.where())
    geopy.geocoders.options.default_ssl_context = ctx
    print "geopy.geocoders.options.default_ssl_context is: ", ctx

If I run this on Windows XP after build same, ie identical code using pyinstaller I get:

  File "OGN-Flogger\src\flogger3.py", line 757, in flogger_start
  File "OGN-Flogger\src\flogger_get_coords.py", line 38, in get_coords
  File "OGN-Flogger\src\flogger_get_coords.py", line 33, in set_ssl_context
AttributeError: 'module' object has no attribute 'options'

I assume pyinstaller is using all the latest modules from the network hence at least the same as on Kubuntu 18.04.
Any idea what's going wrong?

**Comment by tobiz** [comment]
Ok I think I've found the answer which is I had geopy 1.18.0 on Kubuntu and 1.13.0 on Win XP. Having force upgrade to 1.18.0 on Win XP problem solved.
