### ISSUE TITLE
location failure

### ISSUE THREAD

**Issue by titus214inc** [geopy/geopy#337]
This address 11314 Martin Luther King Jr Dr
Cleveland, OH 44105 will not give any geojson data.  I have tried several variations of the address and nothing shows.  Please help.

**Comment by KostyaEsmukov** [comment]
I assume you're trying to retrieve a geojson of a location from Nominatim.

It seems to work for me (although I'm not sure how the `11314 Martin Luther King Jr Dr` street, located in North Carolina, corresponds with the `Cleveland, OH 44105` part of your request, which is located in Ohio).

```
In [1]: import geopy

In [2]: g = geopy.Nominatim(user_agent='specify_your_app_name_here')

In [3]: l = g.geocode('11314 Martin Luther King Jr Dr', geometry='geojson')

In [4]: l
Out[4]: Location(Martin Luther King Jr Drive, Greensboro, Guilford County, North Carolina, 27406, USA, (36.0429483, -79.7735521, 0.0))

In [5]: l.raw['geojson']
Out[5]:
{'type': 'LineString',
 'coordinates': [[-79.774217, 36.044879],
  [-79.773986, 36.044085],
  [-79.7738418, 36.0436694],
  [-79.7736601, 36.0432171],
  [-79.7735521, 36.0429483],
  [-79.7734712, 36.042747],
  [-79.7734174, 36.0426244],
  [-79.7732636, 36.0422742],
  [-79.7731022, 36.0419066],
  [-79.7729465, 36.0415521],
  [-79.77277, 36.04115]]}
```

If you're having an issue with some other address, then this issue should be forwarded to the geocoding service you're using (e.g. Nominatim). geopy has nothing to do with the data itself.

For Nominatim specifically you may find their web interface useful for debugging your queries: https://nominatim.openstreetmap.org/search.php?q=11314+Martin+Luther+King+Jr+Dr&polygon_geojson=1&viewbox=
