### ISSUE TITLE
GeoPy Randomly Failing

### ISSUE THREAD

**Issue by nadroj-isk** [geopy/geopy#346]
I have been using GeoPy for the past month for a project and today it has just stopped working on some of my tests. It seems to break when I initialize it.

![image](https://user-images.githubusercontent.com/37343577/52497059-b39ed680-2b9a-11e9-9aeb-e6c9571f6b8a.png)

**Comment by nadroj-isk** [comment]
![geopy_error](https://user-images.githubusercontent.com/37343577/52497379-8ef72e80-2b9b-11e9-8440-f92c2349a6f5.gif)

For some reason... sometimes it will work and sometimes it wont...I am not sure what is causing this because I've had these tests for a while and they have not broken.

**Comment by KostyaEsmukov** [comment]
This definitely looks like a connectivity issue between your machine and the geocoding service you're using. Closing, as geopy has nothing to do with this.

Consider using [vcrpy](https://vcrpy.readthedocs.io/) in your tests to avoid this kind of issues in future.
