### ISSUE TITLE
Mapbox raw attribute does not contains geocoder response for the place

### ISSUE THREAD

**Issue by inoks** [geopy/geopy#353]
For the Mapbox it would be great to have an exact API response for the place as the `raw` attribute.

I think at that line entire `feature` object needs to be used for the `place` (not just value of the `text`):
https://github.com/geopy/geopy/blob/f452d3763aab88e26f9e8b705e5cbae2dcea349b/geopy/geocoders/mapbox.py#L78

**Comment by lcieslak** [comment]
I was going to open the same issue. The `raw` attribute returns only one value from the response.

![mapbox](https://user-images.githubusercontent.com/15639616/55798263-d4b67180-5ace-11e9-93b9-8f2071d06bca.PNG)

**Comment by KostyaEsmukov** [comment]
Good point! @inoks would you be willing to open a PR with a fix?

**Comment by inoks** [comment]
Sure, here it is #354, please check.

**Comment by inoks** [comment]
Hey @KostyaEsmukov, do you have any estimates on when those changes can be released?
This stops me from using `geopy` at my current project :(

**Comment by KostyaEsmukov** [comment]
@inoks in the meantime you can use geopy from your own fork in your project.

```
pip uninstall geopy
pip install https://github.com/inoks/geopy/archive/patch-1.zip
```
