### ISSUE TITLE
Get NESW of a geo-cordinate in reference to another co-ordinate

### ISSUE THREAD

**Issue by Enforcer007** [geopy/geopy#355]
Request for a feature that can generate NESW for a given geo-cordinate based on a reference geo-cordinate

**Comment by KostyaEsmukov** [comment]
Could you please elaborate or give any references? What does NESW stands for?

**Comment by Enforcer007** [comment]
Hi Esmukov,

Thanks for responding back,

NESW => North, East, South, West.

I was looking for a feature in geopy that can tell me N/E/S/W of a Targeted geo-coordinate in reference to other geo-coordinate, i.e:

Examples:
T: Target and R: Reference

-  New York (T) ; California (R) => East
-  New York (T) ; Mexico City (R) => North
-  Mumbai (T) ; Beijing (R) => West 

I have also looked at other packages for this implementation, but there were none. Therefore I have requested for a feature. 

Anyways, I have developed this functionality myself. 

If you think this feature might be helpful, I'll cr8 a PR for it.

**Comment by zeljkobekcic** [comment]
You can do that with a simple function, but you will need to add some functionality to check and handle if x0 and x1 or y0 and y1 are equal.

```python3
def cardinal_direction(p0: (float, float), p1: (float, float)):
    x0, y0 = p0
    x1, y1 = p1

    is_north = x1 > x0

    # the longitude is defined on a range from (-180, 180) if we
    # have two points p0=(0, 170) and p1=(0, -170) then y1 > y0
    # will return False although we can see on the map that p1 is east
    # of p0. Because of that we need to check if their distance shorter
    # than the maximum of the range they are defined on and if so we
    # need to invert the logic on this
    is_east = (y1 > y0) if abs(y1 - y0) < 180 else (y1 < y0)
    
     return ('N' if is_north else 'S') + ('E' if is_east else 'W')

```

**Comment by Enforcer007** [comment]
This looks very efficient and neat.

**Comment by KostyaEsmukov** [comment]
@Enforcer007 ok, now I get it, thanks for the explanation.

I think this is a very specific (i.e. rarely needed) task which I don't feel is worth having in geopy. I'm open for discussion though.
