### ISSUE TITLE
HK <-> CN country code problem

### ISSUE THREAD

**Issue by hiteshramani** [geopy/geopy#356]
Hi,

I was using the geopy Nominatim for reverse mapping a set of coordinates and for coordinates which map back to Hong Kong, the country code that is returned is CN. Shouldn't HK be returned rather?

**Comment by KostyaEsmukov** [comment]
You should probably ask this on the Nominatim support forum at https://help.openstreetmap.org/. Geopy has nothing to do with the returned data, it's just a Python wrapper for the services' APIs.
