### ISSUE TITLE
colon and slash in postal code for some points when reverse geocoded using Nominatum

### ISSUE THREAD

**Issue by Akshita6** [geopy/geopy#357]
Reverse geocoding location gives postal code for some points as follows: 

`60183/60184` 
`46055:46140`

What does colon and / mean here? Unable to find in documentation anywhere.

**Comment by KostyaEsmukov** [comment]
I've seen your question at SO https://stackoverflow.com/q/55858628 and have left a comment, let's move this discussion there. This is certainly not an issue of geopy.
