### ISSUE TITLE
Geolake: KeyError: 'city'

### ISSUE THREAD

**Issue by nicolaetelecine** [geopy/geopy#366]
Get this error when the request is searching a Canadian zipcode:
```
Traceback (most recent call last):
    loc = geolocator.geocode("H1W 0B4")
  File "C:\Python27\lib\site-packages\geopy\geocoders\geolake.py", line 153, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Python27\lib\site-packages\geopy\geocoders\geolake.py", line 166, in _parse_json
    address = ", ".join([place['city'], place['countryCode']]) 
KeyError: 'city'
```

Found that GeoLake API: https://api.geolake.com/v1/geocode?api_key=my_key&zipcode=H1W%200B4 return no city atribute, here is the sample response:

`{"success":true,"latitude":45.544952,"longitude":-73.546694,"accuracyType":"zipcode","typoCorrected":false,"place":{"countryCode":"CA","countryName":"Canada","currencyCode":"CAD","tld":".ca","languages":"en-CA,fr-CA,iu"}}`

So in this case instead of having an error, the geopy library should return None or empty string!
Fix that issue by modifying line 167 of geolake.py by: 
`address = ", ".join([place.get('city',''), place.get('countryCode','')])`

**Comment by KostyaEsmukov** [comment]
Good catch! Would you like to open a PR with the fix?
