### ISSUE TITLE
Coral Gables, Florida Coordinates Error

### ISSUE THREAD

**Issue by techieslayj** [geopy/geopy#370]
Hello,

I love this library, I just finished a data science project using it to obtain coordinates for my study. The coordinates selected for Coral Gables, Florida were plotted in the ocean, while all my other points were plotted correctly. Just wanted to let you guys know of this error. Once again, excellent job and I will use this library for many projects to come. 

Best,
AJ

**Comment by KostyaEsmukov** [comment]
Thank you for the kind words.

However, geopy has nothing to do with the databases provided by the geocoding services. If you've been using Nominatim geocoder, see here on how to deal with errors in OSM: https://wiki.openstreetmap.org/wiki/Error_reporting
