### ISSUE TITLE
Question: Specify type of location to geocode

### ISSUE THREAD

**Issue by tcco** [geopy/geopy#374]
Using the Nominatim class, is there a way to specify the `class` and `type` of locations that are geocoded? Specifically, I want to specify `class` as place or boundy. Whereas `type` could be equal to city or administrative respectively.

Thanks in advance.

**Comment by KostyaEsmukov** [comment]
According to this answer at https://help.openstreetmap.org/questions/27915/how-to-narrow-the-result-from-nominatim-with-only-cities-and-countries-no-additional-areas

... you can do the following
1. use structured search (which in geopy is accepted as a dict for `query`, see https://geopy.readthedocs.io/en/stable/#geopy.geocoders.Nominatim.geocode)
2. use `featuretype` (however it is currently missing in geopy, and is also absent in Nominatim API docs https://nominatim.org/release-docs/develop/api/Search/)
