### ISSUE TITLE
GeocoderServiceError: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed

### ISSUE THREAD

**Issue by RamySalem1993** [geopy/geopy#376]
When I run the following line of code:

**import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="Ramy", timeout=10000)
location = geolocator.geocode("Nieuwerkerk AD ijssel")
print(type(location))
print(location)
coordinate = [location.longitude, location.latitude]**

I get this error:

**runfile('C:/Users/RSale/OneDrive/Bureaublad/Thesis/Thesis_Python/location_coordinates_try2.py', wdir='C:/Users/RSale/OneDrive/Bureaublad/Thesis/Thesis_Python')
Traceback (most recent call last):

  File "<ipython-input-3-ca37f2e8179a>", line 1, in <module>
    runfile('C:/Users/RSale/OneDrive/Bureaublad/Thesis/Thesis_Python/location_coordinates_try2.py', wdir='C:/Users/RSale/OneDrive/Bureaublad/Thesis/Thesis_Python')

  File "C:\Users\RSale\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\RSale\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/RSale/OneDrive/Bureaublad/Thesis/Thesis_Python/location_coordinates_try2.py", line 6, in <module>
    location = geolocator.geocode("Nieuwerkerk AD ijssel")

  File "C:\Users\RSale\Anaconda3\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one

  File "C:\Users\RSale\Anaconda3\lib\site-packages\geopy\geocoders\base.py", line 386, in _call_geocoder
    raise GeocoderServiceError(message)

GeocoderServiceError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed**

This simple code works two days ago, and now without changing the code it suddenly does not work any more...

**Comment by KostyaEsmukov** [comment]
This is a connectivity issue between your machine and Nominatim, see https://stackoverflow.com/a/16312067

Might be a result of rate limiting too, see their ToS at https://operations.osmfoundation.org/policies/nominatim/

Closing, this is not a problem on geopy side.

**Comment by RamySalem1993** [comment]
The problem is that I did the same on other PC's. For example my work PC. I used a different user_agent, different PC, different Network and still the same error. So, it looks like there is an issue on geopy side. Furthermore, in the past it worked perfect and really quick. Right now, sometimes it gives really slow response, but most of the time the error above.

**Comment by fdriesenaar** [comment]
I had the same behaviour earlier this week, but no more; it now behaves like before, so imho this behaviour originates from the Nominatim service.

I tested it just a couple of minutes before with this code:

```
import geopy.geocoders
geopy.geocoders.options.default_timeout = 3
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geopy_issue_376")

location = geolocator.geocode("Berlin Germany")
print(location.raw)
```

and I got this response:

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>>  RESTART: C:\cygwin64\home\Freek Driesenaar\gitbucket\ecards\python\PyeCard\geopy_test.py 
{'class': 'place', 'lat': '52.5170365', 'boundingbox': ['52.3570365', '52.6770365', '13.2288599', '13.5488599'], 'type': 'city', 'display_name': 'Berlin, 10117, Deutschland', 'osm_type': 'node', 'osm_id': 240109189, 'place_id': 595794, 'importance': 0.932149797630868, 'icon': 'https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.p.20.png', 'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright', 'lon': '13.3888599'}
>>> 
```

**Comment by KostyaEsmukov** [comment]
> So, it looks like there is an issue on geopy side.

How so?

Again, as I said, this is an issue between your side and Nominatim. geopy is a third-party library to the Nominatim project, which takes on maintenance of their infrastructure. 

If you have reasons to believe that there's a problem on Nominatim side, please, contact Nominatim directly. But doing so keep in mind that their service is provided free of charge and, consequently, imposes some restrictions on usage (which I also linked above). So perhaps, if you experience this problem, you'd be better off switching to another service, such as MapQuest.
