### ISSUE TITLE
DeprecationWarning from point.py

### ISSUE THREAD

**Issue by OrangeDog** [geopy/geopy#377]
From Python 3.7, geopy produces this warning

> point.py:264: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

**Comment by KostyaEsmukov** [comment]
This is fixed in geopy 2.0 #335 which will be released later this year.

geopy 1.x won't receive this fix and won't officially support Python 3.9, as this change is incompatible with 2.7.

**Comment by OrangeDog** [comment]
@KostyaEsmukov "later this year" came and went, and the 2.0 milestone has no due date.
Are there any updates on the projected release date?

**Comment by KostyaEsmukov** [comment]
@OrangeDog Yes there are: https://github.com/geopy/geopy/commit/b1eb024c45f1712dbb240bfcd2208498f090ab25

I'm planning on releasing geopy 2.0 very soon. It will definitely be out before cpython 3.9 beta, which is scheduled for May 2020.
