### ISSUE TITLE
Could not parse version info string

### ISSUE THREAD

**Issue by Seha16** [geopy/geopy#380]
```
  File "/home/seha/workspace/a/archer/g/getpackage/getpackage-backend/server/python_backend/backend/.env/lib/python3.6/site-packages/django/contrib/gis/geos/libgeos.py", line 196, in geos_version_info
    raise GEOSException('Could not parse version info string "%s"' % ver)
django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.8.0-CAPI-1.13.1 "
```
Looks like this is a typo from GEOS lib https://trac.osgeo.org/geos
But we can add a workaround from GeoPy side by adding `(\s+)?` at the end of `version_regex`

**Comment by KostyaEsmukov** [comment]
geopy doesn't depend on libgeos and doesn't use it. You seem to have it confused with GeoDjango. These two are completely different libraries.

This might help: https://code.djangoproject.com/ticket/28441
