### ISSUE TITLE
How to cite your work in an academic research?

### ISSUE THREAD

**Issue by farzinghanbari** [geopy/geopy#384]
Hi, I have used geopy for my master's thesis and I want to cite you in my dissertation. Is there anywhere I can find my required information?

**Comment by KostyaEsmukov** [comment]
No, I'm afraid not.

geopy is a little package which has received many contributions from independent developers, so I guess there are no specific people who could be specified as authors for citation.

I, specifically, am out of the scientific loop, so I would not benefit from the citation either.

**Comment by farzinghanbari** [comment]
Thank you for responding.
I will address your repository to acknowledge this library and I appreciate your work.
Best regards.
