### ISSUE TITLE
1.20.0: some Yandex and Nominatim tests fail

### ISSUE THREAD

**Issue by dvzrv** [geopy/geopy#386]
Hi! I'm currently trying to package 1.20.0 for Arch Linux.
I ran into a few failing tests, that I had to disable:

```
FAILED test/geocoders/nominatim.py::NominatimTestCase::test_country_codes_list
FAILED test/geocoders/nominatim.py::NominatimTestCase::test_country_codes_str
FAILED test/geocoders/yandex.py::YandexTestCase::test_params - geopy.exc.Geoc...
FAILED test/geocoders/yandex.py::YandexTestCase::test_reverse - geopy.exc.Geo...
FAILED test/geocoders/yandex.py::YandexTestCase::test_reverse_kind_param - ge...
FAILED test/geocoders/yandex.py::YandexTestCase::test_unicode_name - geopy.ex...
```

The full build and test log is here: 
[python-geopy-1.20.0-build.log](https://github.com/geopy/geopy/files/4068720/python-geopy-1.20.0-build.log)

**Comment by KostyaEsmukov** [comment]
Yep, they're failing in master too. I'm going to get to this next week, apologies for the delay.

Yandex, specifically, started to require an API key, so fixing this requires some changes in code, after which I'll cut a new minor release.

**Comment by KostyaEsmukov** [comment]
Fixed by 87ea08d and ca5aeab: https://travis-ci.org/geopy/geopy/builds/640574006

**Comment by dvzrv** [comment]
Thanks a bunch! :)

**Comment by d3netxer** [comment]
which Yandex API do we need to get?

**Comment by d3netxer** [comment]
I found out that it is the JavaScript API and HTTP Geocoder API

**Comment by KostyaEsmukov** [comment]
`HTTP Geocoder API` should be enough.
