### ISSUE TITLE
Returns 'None' for some addresses I put through processing

### ISSUE THREAD

**Issue by AmeliaJoy** [geopy/geopy#401]
Some error examples:
3390  Mary Street, Coconut Grove, FL
292 S La Cienega Blvd, Beverly Hills, CA
4401  Ringgold Road, Chattanooga, TN
2400  Veterans Blvd, Kenner, LA
17 Ne Skyline , Lee's Summit, MO
2277  Thunderstick Dr, Lexington, KY
301  Yorktown Plaza, Elkins Park, PA
5507  153 , Hixson, TN
2343  Sunnyside Ridge Road, Rancho Palos Verdes, CA
407  Lake Street, Wayzata, MN
4211  Waialae Ave, Kahala Mall, Upper Level, Honolulu, HI
5978  Silvercreek Valley Road, San Jose, CA

**Comment by duarteleonardosales** [comment]
Perhaps they need more details.
Have any of them ever worked at?

**Comment by duarteleonardosales** [comment]
In fact, I searched for addresses at https://www.openstreetmap.org/
I didn't find them.
I think that:
1 - Or more details are missing from the addresses.
2 - Or there is an error in the addresses.
3 - Or the addresses are not cataloged on the website (I think that's it).

**Comment by KostyaEsmukov** [comment]
geopy is a client library for many different geocoding services with their own databases, so any data-related requests and questions should be directed at the support of the geocoding service you're using.
