### ISSUE TITLE
The query of Bing Geocode in Docs

### ISSUE THREAD

**Issue by zhongjun-ma** [geopy/geopy#422]
The key should be "postalCode", not 'postalcode'

**Comment by KostyaEsmukov** [comment]
You are right, the key in the docs shouldn't be lowercased: https://github.com/geopy/geopy/blob/5362fa1a533cb003b44d4f5c51a81f2afc467ea4/geopy/geocoders/bing.py#L105

Would you like to open a PR with a fix? It would be enough to just change that 1 letter. :)

**Comment by KostyaEsmukov** [comment]
Fixed in #424
