### ISSUE TITLE
geopy.distance.vincenty completely deprecated?

### ISSUE THREAD

**Issue by rutvikpensionwar** [geopy/geopy#423]
Is `geopy.distance.vincenty` completely deprecated?

I tried this:
```
import geopy.distance
newport_ri = (41.49008, -71.312796)
cleveland_oh = (41.499498, -81.695391)
print(geopy.distance.vincenty(newport_ri, cleveland_oh).miles)
```

It gave following output
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'geopy.distance' has no attribute 'vincenty'
```

What's the best possible alternative in terms of accuracy?

**Comment by rutvikpensionwar** [comment]
For the time being I am using `geopy.distance.great_circle(newport_ri, cleveland_oh).miles` as the best possible alternative but I am open to other functions like `geodesic`. Let me know.

**Comment by cffk** [comment]
The release notes for 2.0.0 says:

> Removed `geopy.distance.vincenty`, use `geopy.distance.geodesic` instead.

Incidentally `geopy.distance.geodesic` is more accurate than `geopy.distance.vincenty` ever was.

**Comment by KostyaEsmukov** [comment]
Vincenty has been deprecated for over 2 years from now: #293
