### ISSUE TITLE
addressdetails for nominatim is confusingly described

### ISSUE THREAD

**Issue by matkoniecz** [geopy/geopy#425]
https://geopy.readthedocs.io/en/stable/#nominatim

> If you want in Location.raw to include addressdetails such as city_district, etc set it to True

while the most important feature is that it returns address info in a structured form

> If you want in Location.raw to include address details such as house_number, city_district, postcode, etc (in a structured form) set it to True

would be IMHO better description, with original I though that it would include irrelevant detail such as city_district in the textual description (`display_name`), while I needed exactly structured form (I wanted to check whatever response actually matches request)

**Comment by KostyaEsmukov** [comment]
Good point! 

Would you like to submit a PR? The relevant part is here: https://github.com/geopy/geopy/blob/cc3226700632fffce4b934634332e02eefb21f0e/geopy/geocoders/nominatim.py#L178-L179

It would be enough to just update that part of the doc in the PR.
