### ISSUE TITLE
amenity type and name mangled together in response from Nominatim

### ISSUE THREAD

**Issue by matkoniecz** [geopy/geopy#428]
It appears to not be malformed on the Nominatim side: https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=3052053223&class=amenity

```
from geopy.geocoders import Nominatim
import pprint

pp = pprint.PrettyPrinter(indent=4)
geolocator = Nominatim(user_agent="user_agent lalalaa", timeout=100)
response = geolocator.geocode("Gimnazjum w Tykocinie", exactly_one=False, limit=10, addressdetails=True, language="pl,en")
for reply in response:
    pp.pprint(reply.raw)
```

gives (note mangled `amenity` and `name`, into `'amenity': 'Gimnazjum w Tykocinie'`). It appears to be consistently done with schools.

```
{   'address': {   'amenity': 'Gimnazjum w Tykocinie',
                   'country': 'Polska',
                   'country_code': 'pl',
                   'county': 'powiat białostocki',
                   'isolated_dwelling': 'Tamożnia',
                   'municipality': 'gmina Tykocin',
                   'neighbourhood': 'Nowe Miasto',
                   'postcode': '16-080',
                   'road': 'Zagumienna',
                   'state': 'województwo podlaskie',
                   'town': 'Tykocin'},
    'boundingbox': ['53.2059142', '53.2060142', '22.7798701', '22.7799701'],
    'class': 'amenity',
    'display_name': 'Gimnazjum w Tykocinie, Zagumienna, Nowe Miasto, Tamożnia, '
                    'Tykocin, gmina Tykocin, powiat białostocki, województwo '
                    'podlaskie, 16-080, Polska',
    'icon': 'https://nominatim.openstreetmap.org/images/mapicons/education_school.p.20.png',
    'importance': 0.30100000000000005,
    'lat': '53.2059642',
    'licence': 'Data © OpenStreetMap contributors, ODbL 1.0. '
               'https://osm.org/copyright',
    'lon': '22.7799201',
    'osm_id': 3052053223,
    'osm_type': 'node',
    'place_id': 40294715,
    'type': 'school'}
```

**Comment by KostyaEsmukov** [comment]
I'm sorry but I don't quite understand what's the issue.

What do you mean by "mangled together"? There's no such field as `name` in your response.

The `raw` value is the exact response from Nominatim, which is not modified by geopy in any way. So any issues regarding its contents should be directed to Nominatim, see https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service

**Comment by AritzBi** [comment]
I am having a similar issue. What @matkoniecz is trying to explain is that inside address, there should be two properties: name and amenity. As it can been here: https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=3052053223&class=amenity


Name | Gimnazjum w Tykocinie (name)
Type | amenity:school

However, in geopy the value of name is shown in the amenity property:

'amenity': 'Gimnazjum w Tykocinie',

**Comment by matkoniecz** [comment]
@AritzBi is explaining what I tried to report. I admit that I compared Nominatim debug GUI and geopy returned structured, maybe Nominatim actually replies with such broken structure (I have investigating this on my TODO list, but I am unlikely to reach that position before AD 2300)

**Comment by AritzBi** [comment]
@matkoniecz I can confirm that is Nominatim problem. [This ](https://nominatim.openstreetmap.org/reverse?lat=53.2059642&lon=22.7799201&format=json&addressdetails=1)is the query and the response is the one provided by geopy. Anyway, I am going to analyze if changing something in query it provides the correct amenity.
