### ISSUE TITLE
HERE.com's new Geocoding & Search API

### ISSUE THREAD

**Issue by pratheekrebala** [geopy/geopy#430]
Hi @KostyaEsmukov,

Just noticed that HERE.com is no longer maintaining the "Geocoding" API but are instead re-directing folks to use the "Geocoding and Search API". I haven't used both of them extensively but it looks like the new API better handles ambiguous addresses and supports providing component level filtering (e.g. city, county etc). 

Is there any interest in extending support to that API? I can make a PR if you are open to this. Both these APIs are in-compatible so it would either have to break the existing one or create a new Geocoder class (I prefer this approach).

https://developer.here.com/documentation/geocoder/dev_guide/topics/what-is.html

![Screenshot from 2020-07-14 11-37-55](https://user-images.githubusercontent.com/1174162/87445799-7d069000-c5c6-11ea-8d88-666b99d54993.png)

**Comment by KostyaEsmukov** [comment]
I think it might be useful to add a new class for the new API (e.g. `HereV7`). So yeah, a PR would be very welcome!

If they share a lot, then it can be implemented similarly to `BaiduV3` which extends `Baidu`: https://github.com/geopy/geopy/blob/7e276b43fd66d603e8fd0c25313896ee324e1d49/geopy/geocoders/baidu.py#L275-L283

If they don't, it should extend the base geocoder class as the most of the other geocoders.

**Comment by pratheekrebala** [comment]
I think they are just different enough that it might warrant a separate class. I wrote a small wrapper that I have been using internally - I will clean up and make a PR before EOD

**Comment by KostyaEsmukov** [comment]
Fixed via #433
