### ISSUE TITLE
Finding Country from City or State

### ISSUE THREAD

**Issue by seckindinc** [geopy/geopy#431]
Hi,

I am trying to find the country of a city or state. I am getting city and state information from every various countries. The problem i am facing right now is the response is at that countries language and order is changing from country to country.

geolocator.geocode('ANKARA')
Out[8]: Location(Ankara, Çankaya, Ankara, İç Anadolu Bölgesi, 06660, Türkiye, (39.9207774, 32.854067, 0.0))

geolocator.geocode('Hamburg')
Out[12]: Location(Hamburg, Deutschland, (53.5437641, 10.0099133, 0.0))

Issue - 1: Is there a way to directly parse country?
Issue - 2: Is there a way to get English country names?

Regards,

Seckin

**Comment by KostyaEsmukov** [comment]
Please see https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service and https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#reporting-issues.

Questions regarding data should be directed to the geocoding service you're using.
