### ISSUE TITLE
TypeError: __str__ returned non-string (type NoneType)

### ISSUE THREAD

**Issue by dg10a** [geopy/geopy#443]
Here is a minimum example:

```python3:geopy_err_mvp.py
from geopy.geocoders import Nominatim

geolocator = Nominatim(user_agent="TEST_UA")
location = geolocator.geocode({"city": "SACRAMENTO", "state": "CA"})
print(f"Result type: {type(location)}")
print(f"Result str: {location}")
```

Output:
```
> python geopy_err_mvp.py
Result type: <class 'geopy.location.Location'>
Traceback (most recent call last):
  File "geopy_err_mvp.py", line 6, in <module>
    print(f"Result str: {location}")
TypeError: __str__ returned non-string (type NoneType)
```

Versions:
```
python 3.8.5
geopy 1.23.0
```

I haven't dug into this much, but it looks like Nominatim is returning a [strange result](https://nominatim.openstreetmap.org/ui/search.html?city=SACRAMENTO&state=CA). 
`geopy` should return a string regardless.

Related issue in [Nominatim](https://github.com/osm-search/Nominatim/issues/1932).

**Comment by KostyaEsmukov** [comment]
Your code sample works correctly at the moment on my machine:

```
Result type: <class 'geopy.location.Location'>
Result str: Sacramento, Sacramento County, California, United States of America
```

I guess it was a transient issue on the Nominatim side.

In geopy 1.x address indeed could be None, so the error you have demonstrated was possible. However, this has been changed in geopy 2 (d00bb52952057e4c2443cec6bbcb0656bd68e7f8), so theoretically in geopy 2 `geocode` should have raised a TypeError if Nominatim didn't return a correct address.
