### ISSUE TITLE
Consider dropping GeocodeFarm support

### ISSUE THREAD

**Issue by KostyaEsmukov** [geopy/geopy#445]
GeocodeFarm is the only geocoder which tests constantly fail due to the service availability issues. I have observed:
- A week-long expired TLS certificate 
- Sporadic "No results" errors (8ce18b1135cf090a09e388828796a856693603f4)
- Intermittent connection refused errors

In fact, this is the only service for which I had to add an environment variable to allow quickly disabling tests without a commit: a6af73abc831245a394f76acff83a59407e3a28c. And I occasionally have to switch on that env to make the test suite pass.

The current issue is that along with "connection refused" errors the service returns an inadequate address value: #437

I believe that level of service is inappropriate for a public API, so I'm considering removing GeocodeFarm geocoder in geopy 2.2, to avoid anyone wasting their time on a service which is that unstable.

**Comment by KostyaEsmukov** [comment]
Removed in 5ac2473 and will be released as geopy 2.2.

**Comment by APIVersa** [comment]
May I suggest adding it back, as it is now extremely stable and reliable. It was  a downtime issue back then, but was  resolved after the time it was removed from here. There are people still asking to use your solution, but cannot as it isn't in the newer packages, forcing them to use other soultions.
