### ISSUE TITLE
Bing + other geocoders alternative REST interfaces

### ISSUE THREAD

**Issue by elig0n** [geopy/geopy#456]
Bing has an Elevation interface for querying locations' elevations.
It might also be possible that other services are offering multitude of query types & points.
I haven't found if and where it is possible to address these in the geopy API.

**Comment by KostyaEsmukov** [comment]
geopy is not aiming at providing support for all APIs of the geocoding services. Instead only the most common `geocode`/`reverse` methods are implemented for each provider.

If you need to use the less common methods of a provider I would suggest to use their specific library, which usually aims to provide full API support. For Bing the following package seems to provide access to the Elevation API: https://pypi.org/project/bingmaps/
