### ISSUE TITLE
2.1.0: Missing chain of trust for PGP public key A18FE9F6F570D5B4E1E1853FAA7B5406547AF062

### ISSUE THREAD

**Issue by dvzrv** [geopy/geopy#463]
Hi! I'm packaging python-geopy for Arch Linux.

To verify the sources I use the PGP signature that is shipped with each release of geopy.
Previously the signatures have been created using the keypair matching the public key `BE3D633AB6792715ECF34D742D3B9C1712FF84F7`, but for 2.1.0 a new key (`A18FE9F6F570D5B4E1E1853FAA7B5406547AF062`) has been used.
However, the new key is missing a [chain of trust](https://en.wikipedia.org/wiki/Chain_of_trust) (it is not signed by the old key and it seems to be on none of the current keyserver infrastructure).

Additionally, there is an added `Note` line about the old key in [the public key that can be retrieved from github](https://github.com/KostyaEsmukov.gpg) itself:

```
Note: The keys with the following IDs couldn't be exported and need to be reuploaded 2D3B9C1712FF84F7
```

It would be awesome to sort this out, as I am otherwise not able to upgrade the package, due to not being able to verify whether a [supply chain attack](https://en.wikipedia.org/wiki/Supply_chain_attack) is in motion or not.

**Comment by KostyaEsmukov** [comment]
Hi, sorry for the inconvenience.

The previous key `BE3D633AB6792715ECF34D742D3B9C1712FF84F7` has been expired on 2020-07-08, thus I started using a new key `A18FE9F6F570D5B4E1E1853FAA7B5406547AF062`.

> and it seems to be on none of the current keyserver infrastructure

The key is uploaded to the `keys.openpgp.org` keyserver. Let me know if you need me to upload the key somewhere else as well.

> However, the new key is missing a chain of trust (it is not signed by the old key 

I'm not sure how this should have been properly addressed in PGP, but here is a message signed by that older expired key:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi, I'm Kostya Esmukov and I confirm that the A18FE9F6F570D5B4E1E1853FAA7B5406547AF062 PGP key belongs to me
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEEvj1jOrZ5JxXs8010LTucFxL/hPcFAl/3DkMACgkQLTucFxL/
hPe1ug/9E2XZD3J6xm0H/HyY/Gjgu1PlMHWpIgIydtGpa6iHYLPMtqZA8lqrEOZQ
GBKLOFRrgB924iLz/fIb0seJEaXmj1HWjjn22by0S7hboMTyWRtUIWMh91PLMJRn
BYq0f7+8dcRL4DDU0vv8cLaeK1bsxNR/cX4MDTu7EUpdAB+SnvdhjBboQ4pPMZtu
+Fg+c91WX7k/VfER16wOvFjRf30CFGCH/ImGgGPGVLIpoecxh1sJvSI1m8smADd1
Ee+ArOaU9JKAm46swj1WmyOOxFP1knr31DPQl1DU6z0XD4mpSpCM8hc55/X6LvBK
16olY7d7TtuHy9tpWcMT782Lg3zqdH+GiZKU6502KL8ALbQjrMzKOqgg7yW1CW5G
QGPjdo/S9XIm1J8h4W5ZSXuQVI/OvIdCVumnN6uHSG/01uC/TUXTY2wxascXOLhg
9flibJVaXqLuy0YJfi9B6OTj6SbmCQXoYeNJ0BkT5VOAXTszIWX56M42qEksGhAt
2lAtDGIaRSf0cmUxLuVbBuQdmvTDjrIwBVMSiFXniBOUt3l+dC+iqz62CPB0SFg3
w5QF9oP4IIQX8l1rHOhj9E2+mhEmw9mSkMELAEAhP0yfyEhUsVPYyNXbxTJW5itV
/ZDOaq69bJ9f0x7n1Y+nTdvlJ4iv25yMtPBFhL+4M6ie27dA1zM=
=Hkjv
-----END PGP SIGNATURE-----
```

> Additionally, there is an added Note line about the old key in the public key that can be retrieved from github itself:

That's strange. I see both keys added in GitHub. The public key returned by https://github.com/KostyaEsmukov.gpg is correct.

I have just re-uploaded the current key, but the Note doesn't seem to go away. Perhaps it needs some time to update.

**Comment by KostyaEsmukov** [comment]
> I have just re-uploaded the current key, but the Note doesn't seem to go away. Perhaps it needs some time to update.

Oh, I misread the Note. It mentioned the older key, not the new one. Re-uploaded the older key and the Note has gone. Now both keys seem to be present in the output of https://github.com/KostyaEsmukov.gpg.

**Comment by dvzrv** [comment]
Hi @KostyaEsmukov!
Thanks for the prompt reply!

> I'm not sure how this should have been properly addressed in PGP, but here is a message signed by that older expired key:

It is possible to sign another pubkey using your own keypair. In this case you would sign your new key using your old key before revoking the old key. [Here](https://gist.github.com/F21/b0e8c62c49dfab267ff1d0c6af39ab84) is an okay writeup for how to sign a pubkey.
The signed message you provided also works for this specific use-case, but signing your own key is the more general approach to introducing a new key. :)

The SKS infrastructure unfortunately has been in bad shape for a long time, so retrieving keys (and their signatures) can sometimes be quite the hassle. The new way to go about this is to use [WKD](https://wiki.gnupg.org/WKDHosting), which makes the public keys available per domain.

I will close this ticket as my use-case is solved with your provided signed message. However, I suggest still signing your new key with your old key and uploading the new public key again all over the place (which will include the signature) and potentially also looking into WKD to not have to rely on the SKS infastructure in the future anymore.
