### ISSUE TITLE
Update test guidelines for new geocoder patch

### ISSUE THREAD

**Issue by duckontheweb** [geopy/geopy#467]
The [Adding a New Geocoder](https://github.com/geopy/geopy/blob/master/CONTRIBUTING.md#adding-a-new-geocoder) section of the CONTRIBUTING docs direct developers to add the `unittest.skipUnless` decorator and point to the `what3words` tests as an example. However, those test don't utilize the `skipUnless` decorator, and as far as I can tell that decorator is not used in any of the `test/geocoders` tests. 

Should that step be removed from the instructions for contributing a new geocoder?

**Comment by KostyaEsmukov** [comment]
Thank you for pointing this out! Updated the relevant section in 9d38fcc.

**Comment by duckontheweb** [comment]
Perfect, thanks!
