### ISSUE TITLE
How to calculate the coordinates of a point which is 10 miles east to a given point?

### ISSUE THREAD

**Issue by floydluo** [geopy/geopy#473]
How to calculate the coordinates of a point which is 10 miles east to a given point?

Or more formally, using a Latitude and Longitude value (Point A), I am trying to calculate another Point B, X meters away bearing 0 radians from point A. To get the Latitude and Longitude value of Point B?

**Comment by cffk** [comment]
geopy already imports geographiclib to do distance calculations.  It would be reasonable to use the same machinery to solve this problem.  (N.B. if you solve this problem with geodesics, then you specify the *initial* bearing of the path.  If the bearing is due east, then B will end up closer to the equator than A, in general.)

**Comment by KostyaEsmukov** [comment]
geopy already happens to support this, it just wasn't documented before. Added docs in 9c7bf7b, see https://geopy.readthedocs.io/en/latest/#geopy.distance.Distance.destination.

Example with geodesic:

```
>>> import geopy.distance
>>> geopy.distance.geodesic(miles=10).destination((34, 148), bearing=90)
Point(33.99987666492774, 148.17419994321995, 0.0)
```
