### ISSUE TITLE
Any working examples I could see?

### ISSUE THREAD

**Issue by pcsagan** [geopy/geopy#474]
I can't seem to find any working examples. So far all I've been able to find are examples that seem to intentionally throw errors: `geolocator = Nominatim(user_agent="specify_your_app_name_here")`

Can you please provide some working examples of user_agent values?

**Comment by KostyaEsmukov** [comment]
The docs and the error message are pretty explicit about requiring your user-agent to be a custom one, that's why the examples are intentionally not allowed.
