### ISSUE TITLE
Error when computing distance

### ISSUE THREAD

**Issue by tonial** [geopy/geopy#482]
Hello,

I have an issue while computing a distance using geopy. The full stacktrace is at the end.

    geopy.distance.distance((37.336715000000005, -121.91697), (37.336715, -121.9169671))
    > ValueError: math domain error

The code works with less precision :

    geopy.distance.distance((37.336715, -121.91697), (37.336715, -121.9169671))
    Distance(0.0002569911381030601)
    
I not sure if it's an issue with geographiclib or with geopy.
I wanted to report the bug on both libs, but I couldn't find a place to report the issue on geographiclib.

I will probably handle the issue on my side by reducing the precision for each lat/lon (since we don't really need a millimeter precision in our distance so 15 significative numbers is too much), but it still might be a bug somewhere else.

Best Regards

========================================================

The full stacktrace :

    $ geopy.distance.distance((37.336715000000005, -121.91697), (37.336715, -121.9169671))
    
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-2-6e8e3180673e> in <module>
    ----> 1 geopy.distance.distance((37.336715000000005, -121.91697), (37.336715, -121.9169671))
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geopy/distance.py in __init__(self, *args, **kwargs)
        414         self.set_ellipsoid(kwargs.pop('ellipsoid', 'WGS-84'))
        415         major, minor, f = self.ELLIPSOID
    --> 416         super().__init__(*args, **kwargs)
        417 
        418     def set_ellipsoid(self, ellipsoid):
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geopy/distance.py in __init__(self, *args, **kwargs)
        198         elif len(args) > 1:
        199             for a, b in util.pairwise(args):
    --> 200                 kilometers += self.measure(a, b)
        201 
        202         kilometers += units.kilometers(**kwargs)
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geopy/distance.py in measure(self, a, b)
        444             self.geod = Geodesic(self.ELLIPSOID[0], self.ELLIPSOID[2])
        445 
    --> 446         s12 = self.geod.Inverse(lat1, lon1, lat2, lon2,
        447                                 Geodesic.DISTANCE)['s12']
        448 
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geographiclib/geodesic.py in Inverse(self, lat1, lon1, lat2, lon2, outmask)
       1033     """
       1034 
    -> 1035     a12, s12, salp1,calp1, salp2,calp2, m12, M12, M21, S12 = self._GenInverse(
       1036       lat1, lon1, lat2, lon2, outmask)
       1037     outmask &= Geodesic.OUT_MASK
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geographiclib/geodesic.py in _GenInverse(self, lat1, lon1, lat2, lon2, outmask)
        878           # WGS84 and random input: mean = 2.85, sd = 0.60
        879           (v, salp2, calp2, sig12, ssig1, csig1, ssig2, csig2,
    --> 880            eps, domg12, dv) = self._Lambda12(
        881              sbet1, cbet1, dn1, sbet2, cbet2, dn2,
        882              salp1, calp1, slam12, clam12, numit < Geodesic.maxit1_,
    
    ~/dev/.virtualenv/plato/lib/python3.8/site-packages/geographiclib/geodesic.py in _Lambda12(self, sbet1, cbet1, dn1, sbet2, cbet2, dn2, salp1, calp1, slam120, clam120, diffp, C1a, C2a, C3a)
        656     # and subst for calp0 and rearrange to give (choose positive sqrt
        657     # to give alp2 in [0, pi/2]).
    --> 658     calp2 = (math.sqrt(Math.sq(calp1 * cbet1) +
        659                        ((cbet2 - cbet1) * (cbet1 + cbet2) if cbet1 < -sbet1
        660                         else (sbet1 - sbet2) * (sbet1 + sbet2))) / cbet2

    ValueError: math domain error

**Comment by cffk** [comment]
This has been reported before in #466.  It's a result of a bug in `hypot` in python versions 3.[89] and is fixed in python 3.10 and in the next version of geographiclib.

**Comment by tonial** [comment]
And it was the second issue of the list..... I think I read the opened issues a bit too fast.
Thank you for your quick answer, and I'm sorry about the noise.
I'm closing the issue.
