### ISSUE TITLE
Update Here Geocoder to use API version 7

### ISSUE THREAD

**Issue by Tafkas** [geopy/geopy#487]
The Here geocoder uses the API version v6, which is no longer actively develeoped and only available in maintenance mode: 

https://developer.here.com/documentation/geocoder/dev_guide/topics/what-is.html

The new version of the geocoder is 7: https://developer.here.com/documentation/geocoding-search-api/api-reference-swagger.html

https://developer.here.com/documentation/geocoding-search-api/migration_guide/index.html

**Comment by Tafkas** [comment]
I've just noticed that the code is already in the master branch. I guess we just have to wait for a new tag 2.2 to be released.

**Comment by syphar** [comment]
@ijl @KostyaEsmukov is there any way to release this update? 

Is there anything we can support with?

**Comment by KostyaEsmukov** [comment]
I'll try to get my hands on making a release this week.

**Comment by KostyaEsmukov** [comment]
Released `geopy=2.2.0`.
