### ISSUE TITLE
Nominatim always return "None"

### ISSUE THREAD

**Issue by aleborba** [geopy/geopy#49]
I am trying to use OSM but I always get "None" on the result

``` python
from geopy.geocoders import Nominatim

geolocator = Nominatim()

address, (latitude, longitude) = geolocator.geocode('Avenida Paulista, Cerqueira Cesar Sao Paulo')
```

I got this error:

```
TypeError: 'NoneType' object is not iterable
```

**Comment by patrickm663** [comment]
Very old post but raising an exception would be very helpful. It was only picked up that the address didn't exist because elsewhere in my code it produced an error that I had been passing `None` around.

**Comment by KostyaEsmukov** [comment]
> Very old post but raising an exception would be very helpful. It was only picked up that the address didn't exist because elsewhere in my code it produced an error that I had been passing `None` around.

1. It's explicitly documented, e.g. here: https://geopy.readthedocs.io/en/latest/#module-geopy.geocoders
2. None seems to be more convenient for the common usecase which is notebook/pandas oriented.
