### ISSUE TITLE
Explanation of geopy.destination

### ISSUE THREAD

**Issue by ashutosh-adhzm** [geopy/geopy#492]
Thank you for the wonderful work.
I would like to understand which model and formula are used to calculate the final position given initial location, bearing and distance? I checked that earlier geopy used Vincenty, which is now deprecated. Basically, I would like to understand the theory. Any reference/explanation of would be helpful.

Thank you!

**Comment by cffk** [comment]
The distance and destination capabilities of geopy leverage the python package geographiclib.  This implements the methods described in my paper "Algorithms for geodesics", J. Geodesy 87(1), 43–55 (2013), [doi:10.1007/s00190-012-0578-z](https://doi.org/10.1007/s00190-012-0578-z).

**Comment by ashutosh-adhzm** [comment]
Great! Thanks a lot!!
