### ISSUE TITLE
Geocoder MapBox fails using token with URL restriction

### ISSUE THREAD

**Issue by dennisstritzke** [geopy/geopy#500]
When creating [an access token on MapBox](https://account.mapbox.com/access-tokens/) and adding any URL restriction, we have no (default) way of telling geopy about the restriction, which results in a `GeocoderInsufficientPrivileges` exception when executing a geocode request.

Executing geocoding requests using unrestricted tokens works just fine.

The Mapbox API expects the `Referer` header to match an URL that the calling token is restricted to. If I create the MapBox geocoder and set the `Referer` header via the `headers` field, the API call succeeds.

Find unit tests below to illustrate these points.

I propose to add an optional constructor parameter `request_origin_url` that includes its value in the HTTP `Referer` header, if the parameter is provided.

```python
def test_mapbox_geocode():
    geo_locator = MapBox(api_key=api_key_localhost)
    geo_locator.headers["Referer"] = "http://localhost:8000"
    geo_locator.geocode("Frankfurt")

def test_mapbox_geocode__without_referer():
    with pytest.raises(geopy.exc.GeocoderInsufficientPrivileges):
        geo_locator = MapBox(api_key=api_key_localhost)
        geo_locator.geocode("Frankfurt")
```

**Comment by KostyaEsmukov** [comment]
Thank you!
