### ISSUE TITLE
`country_bias` parameter to Pelias is misleading

### ISSUE THREAD

**Issue by orangejulius** [geopy/geopy#504]
Hi! Pelias maintainer here.

The Pelias geocoder class in geopy includes a `country_bias` parameter on the search function:

https://github.com/geopy/geopy/blob/af0eedcfeb4e3eec88f19e2f822e7f14ac3468eb/geopy/geocoders/pelias.py#L112

 However, Pelias only includes the [`boundary.country`](https://github.com/pelias/documentation/blob/master/search.md#search-within-a-particular-country) parameter, which is a _hard filter_. It will only ever return results from the countries listed in the parameter.

`bias` implies it might be a soft filter, that would include results from other countries under certain circumstances, so in this case it might be a bit misleading.

I'm happy to open a PR to update the documentation, but should we consider renaming the parameter? What's the process for that? Let me know if I can help with some PRs. Thanks!

**Comment by KostyaEsmukov** [comment]
Hi, this is a very good catch, thank you! I certainly agree that this naming is misleading given that the filter is hard.

I have added a new argument `countries` accepting a python list of strings -- the country names, and have added a deprecation warning for `country_bias` suggesting to use the `countries` arg instead.

Thank you so much for linking the relevant Pelias documentation section which made the change easier for me!
