### ISSUE TITLE
"B1 1AA" postcode

### ISSUE THREAD

**Issue by garrydoherty84** [geopy/geopy#509]
The following code segment is returning me a latitude and longitude in Poland when I was expecting Birmingham, UK.

```
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="test_app")
geo = geolocator.geocode("B1 1AA")
```
The returned latitude and longitude are:
**latitude: 54.3848128, longitude: 18.7214428**

Any thoughts?

**Comment by KostyaEsmukov** [comment]
This looks like a Nominatim issue, see https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service

Although I'm not quite sure how should a search index covering the whole planet assume that this obscure string is expected to match something in the UK specifically.
