### ISSUE TITLE
float to string conversion issue (engineering format) with `Nominatim.reverse`

### ISSUE THREAD

**Issue by okleinke** [geopy/geopy#511]
# Description

There seems to be an issue when calling `Nominatim.reverse` with coordinates that are close to 0.0. The coordinates are converted to string format when the query is formed. Coordinates that are within 1.e-4 around zero are converted to engineering format (with an `e`). Nominatim rejects such coordinates with message:

> 400 - Floating-point number expected for parameter 'lon'

Example query that exhibits the message:

https://nominatim.openstreetmap.org/reverse?lat=50.0&lon=-1.0e-5

# Replication

```python
import geopy

n = geopy.Nominatim(user_agent="Manual Debug Test")

# works
n.reverse((50.0, -1.0e-3))

# fails
n.reverse((50.0, -1.0e-5))
```

# Proposed solution

In line: https://github.com/geopy/geopy/blob/master/geopy/geocoders/nominatim.py#L343

Provide the optional `output_format` argument to `Geocoder._coerce_point_to_string` that defines a fixed point format pattern with precision of 6 decimal places. (Roughly equals a resolution of 10cm)

# Configuration

Tested with geopy version 2.2.0, Python 3.9.10

**Comment by KostyaEsmukov** [comment]
Thanks for the great report and an example!
