### ISSUE TITLE
Make Distance objects hashable

### ISSUE THREAD

**Issue by jachymb** [geopy/geopy#514]
In my project I wanted to use a `Distance` instance as a dict key, but it's not possible because the `__hash__` method is not implented. I believe this should be easy to do - just return the `hash` of the underlying numeric representation.

**Comment by TomGoBravo** [comment]
This looks like a duplicate of https://github.com/geopy/geopy/issues/485

**Comment by KostyaEsmukov** [comment]
Closing as a duplicate of #485
