### ISSUE TITLE
Wrong location returned - State seems to be ignored

### ISSUE THREAD

**Issue by yelskiy** [geopy/geopy#523]
Using `geopy` version 2.2.0

Code:
```
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent='myapplication')
geolocator.geocode("Norwood MA")
```
Expected
```
Location(Norwood, Norfolk County, Massachusetts, 02062, United States, (42.194543, -71.1994976, 0.0))
```
Got
```
Location(Norwood, Peoria County, Illinois, United States, (40.7055931, -89.6987129, 0.0))
```

I have tried a couple other towns - Canton MA and Westwood MA, and also got wrong locations.

**Comment by KostyaEsmukov** [comment]
Sorry but this is not the right place for such reports. https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service

**Comment by yelskiy** [comment]
> Sorry but this is not the right place for such reports. https://geopy.readthedocs.io/en/stable/#geopy-is-not-a-service

Ah!  My bad!

**Comment by yelskiy** [comment]
@KostyaEsmukov just a heads up about this issue in `Nominatim` -  the API can't correctly handle applying the `limit` parameter, and the "solution" (workaround) is to just get all results and return first.

https://github.com/osm-search/Nominatim/issues/882#issuecomment-358127138
https://github.com/osm-search/Nominatim/issues/2790#issuecomment-1209017965
