### ISSUE TITLE
Very many instances of ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out

### ISSUE THREAD

**Issue by valeriupredoi** [geopy/geopy#545]
hey guys, we are observing a large number of HTTP request timeout-related fails, when using the geolocator over CI, see for instance, all these tests failed in a single large [testing session](https://github.com/ESMValGroup/ESMValCore/actions/runs/4684335504) - the problem is basically from two lines (here "Berlin" is an example location, the actual location is not a factor causing timeouts):
```python
        from geopy.geocoders import Nominatim
        
        
        geolocator = Nominatim(user_agent='esmvalcore')
        geolocator.geocode("Berlin")
```

- we are installing `geopy` from conda-forge, with version `geopy=2.3.0`. These issues were sporadic, if at all frequent a couple weeks before Easter, but then we noticed a massive increase in the number of fails over the Easter break (possibly high traffic for geolocation - people traveling on holidays?), and now it's still pretty bad with most our tests failing due to this. I have created a special pytest marker to skip these tests, when they fail, but still - it's not normal behaviour. Do you know why is this happening? Many thanks in advance :beer:

**Comment by pstatonwx** [comment]
I am also receiving this error when trying to do a reverse address:
```
address = geolocator.reverse(location).address
```

**Comment by grekichi** [comment]
Is this error not solved yet ?

**Comment by grekichi** [comment]
Hi pstatonwx.
Thanks for comment.
Does your meaning , already modifed code in geopy ?
Or have to use mocked py data ?
which ?

**Comment by valeriupredoi** [comment]
sorry guys, I gotta close this - the cause of my problem was I using the Nominatim location finder over CI, which goes against the fair use policy. My apologies for that, we stopped doing that when we found out that what we were doing was against the fiar use policy so now we're simply mocking in the CI :+1:
