### ISSUE TITLE
importing geopy takes a long time

### ISSUE THREAD

**Issue by crockeea** [geopy/geopy#548]
```
import time
start = time.time()
import geopy
print("Importing geopy took %.1f seconds" % (time.time()-start))
```
This prints `Importing geopy took 3.1 seconds`. This adds considerable overhead to my program.

**Comment by KostyaEsmukov** [comment]
What do you expect should be done on the geopy's side to improve this?

I believe this must be an issue specific to your environment, as there's nothing heavy or special is going on in geopy. On my system the import takes 0.2s.

**Comment by crockeea** [comment]
The main problem for me is that I was using a virtual environment on the Windows file system, but using Python in WSL. This dramatically degrades performance.
