### ISSUE TITLE
Signed releases for downstreams

### ISSUE THREAD

**Issue by dvzrv** [geopy/geopy#550]
Hi! I package this project for Arch Linux.

With the recent policy change, PyPi broke the reproducibility of downstreams: https://blog.pypi.org/posts/2023-05-23-removing-pgp/

As signatures are now no longer available on the platform, builds of projects from there are failing. This is a super sad state of affairs for downstream transparency and verification and we'll have to work through quite a lot of tickets such as this one: https://bugs.archlinux.org/task/79083

Do you plan on providing signatures for tarballs on github going forward? If so, doing a release would unblock me on that topic.

Thanks for you consideration!

**Comment by dvzrv** [comment]
FWIW, I will switch to signed git tags for the time being. Do note, that for some downstreams this may not be an option.

**Comment by KostyaEsmukov** [comment]
Hi! Thank you for letting me know about this change! It's indeed a concerning move on PyPi's part.

> Do you plan on providing signatures for tarballs on github going forward? 

Sure, I'm open to it. I will include this in the release process for the next release.

> If so, doing a release would unblock me on that topic.
> FWIW, I will switch to signed git tags for the time being. Do note, that for some downstreams this may not be an option.

I hadn't planned on doing a new release anytime soon, but from what I understood, this is no longer blocking you since the signed git tags worked for you.

**Comment by KostyaEsmukov** [comment]
https://github.com/geopy/geopy/releases/tag/2.4.0 has just been released with a signature attached to the GitHub release. This step is now also incorporated into the release checklist: 4fd273a
