### ISSUE TITLE
DataBC URL is depreceted since 2020

### ISSUE THREAD

**Issue by nrogers-rew** [geopy/geopy#556]
```
December 1, 2020
The following URLs were deprecated on Sep. 1, 2018 and are now shut down:

http://apps.gov.bc.ca/pub/geocoder
https://apps.gov.bc.ca/pub/geocoder
This URL should now be used, with or without an API key: https://geocoder.api.gov.bc.ca
```
As of August 22, 2023 (lol), the http url above has started getting 104 CONNECTION RESET. The deprecated https url still works as of the same date, but that is not guaranteed to continue.

**Comment by KostyaEsmukov** [comment]
Geocoder's domain has been updated via #557
