### ISSUE TITLE
Aeronautical co-ordinates format Nddmmss.ss Wdddmmss.ss

### ISSUE THREAD

**Issue by jmb** [geopy/geopy#57]
In many aeronautical publications (such as the UK AIP - http://www.ais.org.uk) the co-ordinate system used is Nddmmss.ss Wdddmmss.ss with or without the decimal seconds.

When passed to Point as a string, the whole gets interpreted as degrees and then converted back to 360/180 degrees as (normally) appropriate.

Is this a co-ordinate system that can be added to geopy?

I have a patch for the parse_degrees class method of the Point class which checks the format and splits it up appropriately, but I'm not sure if this is the right place.

**Comment by ijl** [comment]
@jmb feel free to reopen this, but for now closing as inactive.
