### ISSUE TITLE
geopy doesn't support address string in Chinese characters

### ISSUE THREAD

**Issue by sean72kimo** [geopy/geopy#78]
Hope geopy can support different string char

**Comment by solumos** [comment]
Ah, sometimes Nominatim results in a geopy.exc.GeocoderTimedOut with the default timeout parameter set to 1. Try this:

    from geopy.geocoders import Nominatim
    geolocator = Nominatim()
    location = geolocator.geocode("台北市中正區北平西路3號", timeout=10)
    location = geolocator.geocode("No.3, Beiping W. Rd., Jhongjheng District, Taipei City 100, Taiwan", timeout=10)

**Comment by hungwei0331** [comment]
@sean72kimo

Hello, i would like to ask did you solved this issue finally ?
