### ISSUE TITLE
How to choose which geocoding provider to use?

### ISSUE THREAD

**Issue by cameronehrlich** [geopy/geopy#90]
There are a lot of provider options to chose from, but there is nothing in the documentation to suggest a reason for using any one of them in particular.  Are some of the providers more accurate? Are some faster? Are some of them more rate limited than others?

**Comment by bigsassy** [comment]
You have to be careful though. Google's API requires you to use the data only on their maps (e.g NOT open street maps, mapbox, etc).  Which means you can only display it on a publicly available google map which doesn't require a login, or pay for Google Maps API for Business at $10,000 a year.

**Comment by LennyLip** [comment]
Yandex geocoding data also must not be stored in your database (only cache) and must use only on public yandex maps in your service. Also Yandex geocoder API have limit for 25000 requests per day.

**Comment by ijl** [comment]
If anyone'd like to add to the docs explaining what you need to be aware of when choosing a service, that'd be welcome.

**Comment by LennyLip** [comment]
Yandex.Maps API Terms of Use - http://legal.yandex.com/maps_api/

**Comment by KostyaEsmukov** [comment]
I'm closing this in favor of #268
