### ISSUE TITLE
Geocoding Queue That Respects Rate Limits?

### ISSUE THREAD

**Issue by jackmaney** [geopy/geopy#99]
First of all, I *love* this package. Many thanks to the contributors and maintainers.

While using it, I've found myself building a [simple wrapper class](https://gist.github.com/jackmaney/4a98cfdfef61e1d5a097) that geocodes a list of addresses and enforces a per-second rate limit (the actual version that I'm using has a few more bells and whistles, but this is the basic idea). The resulting object takes a `geocoder` object and uses the geopy api (namely calling a `geocode` method on the `geocoder` and passing in an address from the given list).

Would a pull request to add such a class be welcome?

**Comment by jackmaney** [comment]
I've taken the liberty to create [a Python package](https://github.com/jackmaney/rate-limited-queue/) that provides a general rate-limited queue. It may be a bit rough around the edges for the moment, but it allows the processing (given via a user-specified function) of a list of items that respects one or more rate limits (so one could, eg, enforce a per-second and per-day rate limit).

**Comment by ijl** [comment]
@jackmaney, now that there's a package, if you'd like to document your its availability and use in geopy, that'd be welcome. It looks quite useful.

By the way, if I rewrote the geocoders from scratch, I'd think creating composable request, rate limit, and serialization objects on the geocoders would work better than the current template approach. That may not quite work with the wrapper approach, but would solve some issues such as not being able to choose whether you use, e.g., urllib or requests.

**Comment by ijl** [comment]
Closing as inactive. Feel free to reopen.
